/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateSessionCookie200Response : Response containing the created session cookie.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionCookie200Response {
    /// The session cookie value. Set this as an HTTP-only, secure cookie in your web application.
    #[serde(rename = "sessionCookie", skip_serializing_if = "Option::is_none")]
    pub session_cookie: Option<String>,
    /// When the session cookie expires.
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl CreateSessionCookie200Response {
    /// Response containing the created session cookie.
    pub fn new() -> CreateSessionCookie200Response {
        CreateSessionCookie200Response {
            session_cookie: None,
            expires_at: None,
        }
    }
}
