/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateAppRequest : Request body for creating a new app.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAppRequest {
    /// Human-readable display name for the app. Required.
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// Target platform for an app.
    #[serde(rename = "platform")]
    pub platform: Platform,
    #[serde(rename = "ios", skip_serializing_if = "Option::is_none")]
    pub ios: Option<Box<models::ListApps200ResponseAppsInnerIos>>,
    #[serde(rename = "android", skip_serializing_if = "Option::is_none")]
    pub android: Option<Box<models::ListApps200ResponseAppsInnerAndroid>>,
    #[serde(rename = "macos", skip_serializing_if = "Option::is_none")]
    pub macos: Option<Box<models::ListApps200ResponseAppsInnerMacos>>,
    #[serde(rename = "windows", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<models::ListApps200ResponseAppsInnerWindows>>,
    #[serde(rename = "linux", skip_serializing_if = "Option::is_none")]
    pub linux: Option<Box<models::ListApps200ResponseAppsInnerLinux>>,
    #[serde(rename = "web", skip_serializing_if = "Option::is_none")]
    pub web: Option<Box<models::ListApps200ResponseAppsInnerWeb>>,
}

impl CreateAppRequest {
    /// Request body for creating a new app.
    pub fn new(display_name: String, platform: Platform) -> CreateAppRequest {
        CreateAppRequest {
            display_name,
            platform,
            ios: None,
            android: None,
            macos: None,
            windows: None,
            linux: None,
            web: None,
        }
    }
}
/// Target platform for an app.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "IOS")]
    Ios,
    #[serde(rename = "ANDROID")]
    Android,
    #[serde(rename = "MACOS")]
    Macos,
    #[serde(rename = "WINDOWS")]
    Windows,
    #[serde(rename = "LINUX")]
    Linux,
    #[serde(rename = "WEB")]
    Web,
}

impl Default for Platform {
    fn default() -> Platform {
        Self::Ios
    }
}
