/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateCustomTokenRequest : Request body for creating a custom token. Custom tokens allow server-side authentication of users when you manage your own user database or need to integrate with external identity providers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomTokenRequest {
    /// The pistachio_id of the user to create the token for. Must be a valid user within the project.
    #[serde(rename = "pistachioId")]
    pub pistachio_id: String,
    /// Optional tenant ID if the user belongs to a tenant. Required for multi-tenant projects.
    #[serde(
        rename = "tenantId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant_id: Option<Option<String>>,
    /// Optional additional claims to include in the custom token. These claims will be merged with the user's existing custom claims. Reserved claim names (iss, sub, aud, exp, iat, nbf) cannot be overwritten.
    #[serde(rename = "additionalClaims", skip_serializing_if = "Option::is_none")]
    pub additional_claims: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Token validity duration in seconds. Default is 3600 (1 hour). Maximum is 86400 (24 hours).
    #[serde(rename = "expiresIn", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<i32>,
}

impl CreateCustomTokenRequest {
    /// Request body for creating a custom token. Custom tokens allow server-side authentication of users when you manage your own user database or need to integrate with external identity providers.
    pub fn new(pistachio_id: String) -> CreateCustomTokenRequest {
        CreateCustomTokenRequest {
            pistachio_id,
            tenant_id: None,
            additional_claims: None,
            expires_in: None,
        }
    }
}
