/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateApiKey201Response : Response containing the newly created API key. IMPORTANT: The full `keyString` is only returned in this response. Store it securely as it cannot be retrieved again.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKey201Response {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Box<models::CreateApiKey201ResponseApiKey>>,
}

impl CreateApiKey201Response {
    /// Response containing the newly created API key. IMPORTANT: The full `keyString` is only returned in this response. Store it securely as it cannot be retrieved again.
    pub fn new() -> CreateApiKey201Response {
        CreateApiKey201Response { api_key: None }
    }
}
