/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateProjectRequest : Request body for creating a new project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectRequest {
    /// Desired project ID. If not provided, one will be generated. Must be 6-30 characters, lowercase alphanumeric with hyphens.
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Human-readable display name. If not provided, projectId will be used as the display name.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Invitation code for project creation. Must be a valid 16 hex character code. Required for gated project creation.
    #[serde(rename = "invitationCode", skip_serializing_if = "Option::is_none")]
    pub invitation_code: Option<String>,
}

impl CreateProjectRequest {
    /// Request body for creating a new project.
    pub fn new() -> CreateProjectRequest {
        CreateProjectRequest {
            project_id: None,
            display_name: None,
            invitation_code: None,
        }
    }
}
