/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateServiceAccountRequest : Request body for creating a service account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateServiceAccountRequest {
    /// Desired service account ID. If not provided, one will be generated. Must be 4-128 characters, lowercase alphanumeric with hyphens.
    #[serde(rename = "serviceAccountId", skip_serializing_if = "Option::is_none")]
    pub service_account_id: Option<String>,
    /// Human-readable display name. Required.
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// Optional description of the service account's purpose.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreateServiceAccountRequest {
    /// Request body for creating a service account.
    pub fn new(display_name: String) -> CreateServiceAccountRequest {
        CreateServiceAccountRequest {
            service_account_id: None,
            display_name,
            description: None,
        }
    }
}
