/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateCustomToken200Response : Response containing the created custom token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomToken200Response {
    /// The custom token (JWT) that can be used to sign in the user. Exchange this token for an ID token using the token exchange endpoint.
    #[serde(rename = "customToken", skip_serializing_if = "Option::is_none")]
    pub custom_token: Option<String>,
}

impl CreateCustomToken200Response {
    /// Response containing the created custom token.
    pub fn new() -> CreateCustomToken200Response {
        CreateCustomToken200Response { custom_token: None }
    }
}
