/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateApiKey201ResponseApiKey : An API key for authenticating client SDK requests. API keys identify the project and app making requests.  IMPORTANT: The full `keyString` is only returned when creating or rotating a key. For security, subsequent GET requests return only a masked prefix.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKey201ResponseApiKey {
    /// Resource name in the format: \"projects/{project_id}/apps/{app_id}/apiKeys/{key_id}\"
    #[serde(rename = "name")]
    pub name: String,
    /// Unique key identifier.
    #[serde(rename = "keyId")]
    pub key_id: String,
    /// The full API key string to use for authentication. This is the value that should be passed in the `key` query parameter. IMPORTANT: This is only returned once at creation/rotation time. Store it securely as it cannot be retrieved again.
    #[serde(rename = "keyString")]
    pub key_string: String,
    /// Human-readable display name for the key.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Box<models::ListApiKeys200ResponseApiKeysInnerRestrictions>>,
    /// Timestamp when the key was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Timestamp when the key was last updated.
    #[serde(
        rename = "updatedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
}

impl CreateApiKey201ResponseApiKey {
    /// An API key for authenticating client SDK requests. API keys identify the project and app making requests.  IMPORTANT: The full `keyString` is only returned when creating or rotating a key. For security, subsequent GET requests return only a masked prefix.
    pub fn new(
        name: String,
        key_id: String,
        key_string: String,
        created_at: String,
    ) -> CreateApiKey201ResponseApiKey {
        CreateApiKey201ResponseApiKey {
            name,
            key_id,
            key_string,
            display_name: None,
            restrictions: None,
            created_at,
            updated_at: None,
        }
    }
}
