/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateTenantRequest : Request body for creating a new tenant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTenantRequest {
    /// Desired tenant ID. If not provided, one will be generated. Must be 1-128 characters, alphanumeric with underscores, case-sensitive.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Human-readable display name. Max 256 characters. If not provided or null, a friendly name will be generated based on the tenant ID, or a random adjective-noun pair if the tenant ID is auto-generated.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// Whether PDPKA sign-up is allowed. Defaults to true if not specified.
    #[serde(rename = "allowPdpkaSignup", skip_serializing_if = "Option::is_none")]
    pub allow_pdpka_signup: Option<bool>,
    /// Whether authentication is disabled. Defaults to false if not specified.
    #[serde(rename = "disableAuth", skip_serializing_if = "Option::is_none")]
    pub disable_auth: Option<bool>,
    /// Enabled MFA providers for this tenant. Valid values: \"phone\", \"totp\"
    #[serde(rename = "mfaConfig", skip_serializing_if = "Option::is_none")]
    pub mfa_config: Option<Vec<MfaConfig>>,
}

impl CreateTenantRequest {
    /// Request body for creating a new tenant.
    pub fn new() -> CreateTenantRequest {
        CreateTenantRequest {
            tenant_id: None,
            display_name: None,
            allow_pdpka_signup: None,
            disable_auth: None,
            mfa_config: None,
        }
    }
}
/// Enabled MFA providers for this tenant. Valid values: \"phone\", \"totp\"
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaConfig {
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "totp")]
    Totp,
}

impl Default for MfaConfig {
    fn default() -> MfaConfig {
        Self::Phone
    }
}
