/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateProject200ResponseProject : Top-level container for apps, users, and resources. Projects provide isolated namespaces for authentication, data storage, and other platform services.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProject200ResponseProject {
    /// Resource name in the format \"projects/{project_id}\".
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unique project identifier. Immutable after creation.
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Internal project identifier. 16 bytes encoded as 32 hex characters ending in '01'.
    #[serde(rename = "pistachioId", skip_serializing_if = "Option::is_none")]
    pub pistachio_id: Option<String>,
    /// Human-readable display name. Max 64 characters.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Lifecycle state of a project.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::CreateProject200ResponseProjectResources>>,
    /// Timestamp when the project was created.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the project was last updated.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl CreateProject200ResponseProject {
    /// Top-level container for apps, users, and resources. Projects provide isolated namespaces for authentication, data storage, and other platform services.
    pub fn new() -> CreateProject200ResponseProject {
        CreateProject200ResponseProject {
            name: None,
            project_id: None,
            pistachio_id: None,
            display_name: None,
            state: None,
            resources: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// Lifecycle state of a project.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DELETED")]
    Deleted,
}

impl Default for State {
    fn default() -> State {
        Self::Active
    }
}
