/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateApp200Response : Response containing the newly created app with API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApp200Response {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::ListApps200ResponseAppsInner>>,
}

impl CreateApp200Response {
    /// Response containing the newly created app with API key.
    pub fn new() -> CreateApp200Response {
        CreateApp200Response { app: None }
    }
}
