/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// CreateProjectUserRequest : Request body for creating a new user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectUserRequest {
    /// User's primary email address.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the email has been verified. Defaults to false.
    #[serde(rename = "emailVerified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    /// User's phone number in E.164 format.
    #[serde(
        rename = "phoneNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// Human-readable display name. Max 256 characters.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// URL to the user's profile photo.
    #[serde(
        rename = "photoUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub photo_url: Option<Option<String>>,
    /// Whether the account is disabled. Defaults to false.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Custom claims for the ID token.
    #[serde(rename = "customClaims", skip_serializing_if = "Option::is_none")]
    pub custom_claims: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CreateProjectUserRequest {
    /// Request body for creating a new user.
    pub fn new() -> CreateProjectUserRequest {
        CreateProjectUserRequest {
            email: None,
            email_verified: None,
            phone_number: None,
            display_name: None,
            photo_url: None,
            disabled: None,
            custom_claims: None,
        }
    }
}
