/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// DeleteApp200Response : Response containing the soft-deleted app.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteApp200Response {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::ListApps200ResponseAppsInner>>,
}

impl DeleteApp200Response {
    /// Response containing the soft-deleted app.
    pub fn new() -> DeleteApp200Response {
        DeleteApp200Response { app: None }
    }
}
