/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// DeleteProject200Response : Response containing the soft-deleted project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteProject200Response {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::ListProjects200ResponseProjectsInner>>,
}

impl DeleteProject200Response {
    /// Response containing the soft-deleted project.
    pub fn new() -> DeleteProject200Response {
        DeleteProject200Response { project: None }
    }
}
