/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// EnableServiceAccountKey200Response : Response containing the re-enabled key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnableServiceAccountKey200Response {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<models::ListServiceAccountKeys200ResponseKeysInner>>,
}

impl EnableServiceAccountKey200Response {
    /// Response containing the re-enabled key.
    pub fn new() -> EnableServiceAccountKey200Response {
        EnableServiceAccountKey200Response { key: None }
    }
}
