/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// GenerateServiceAccountKey201Response : Response containing the newly generated key. IMPORTANT: The privateKeyData is only returned once and cannot be retrieved again.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateServiceAccountKey201Response {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<models::GenerateServiceAccountKey201ResponseKey>>,
    /// Base64-encoded private key data in PKCS#8 format. This is only returned once at key creation time.
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "privateKeyData", skip_serializing_if = "Option::is_none")]
    pub private_key_data: Option<Vec<u8>>,
    /// JSON key file contents for SDK authentication. Contains the private key and service account metadata. This is only returned once at key creation time.
    #[serde(rename = "keyFileJson", skip_serializing_if = "Option::is_none")]
    pub key_file_json: Option<String>,
}

impl GenerateServiceAccountKey201Response {
    /// Response containing the newly generated key. IMPORTANT: The privateKeyData is only returned once and cannot be retrieved again.
    pub fn new() -> GenerateServiceAccountKey201Response {
        GenerateServiceAccountKey201Response {
            key: None,
            private_key_data: None,
            key_file_json: None,
        }
    }
}
