/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GenerateServiceAccountKey201ResponseKey : A key for service account authentication. Keys are used to generate JWTs for authenticating as the service account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateServiceAccountKey201ResponseKey {
    /// Resource name in the format: \"projects/{project_id}/serviceAccounts/{service_account_id}/keys/{key_id}\"
    #[serde(rename = "name")]
    pub name: String,
    /// Unique key identifier.
    #[serde(rename = "keyId")]
    pub key_id: String,
    /// The algorithm used for the key pair.
    #[serde(rename = "keyAlgorithm")]
    pub key_algorithm: KeyAlgorithm,
    /// How the key was created.
    #[serde(rename = "keyOrigin", skip_serializing_if = "Option::is_none")]
    pub key_origin: Option<KeyOrigin>,
    /// The key becomes valid at this time.
    #[serde(rename = "validAfterTime")]
    pub valid_after_time: String,
    /// The key expires at this time. Null means no expiration.
    #[serde(
        rename = "validBeforeTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub valid_before_time: Option<Option<String>>,
    /// Whether the key is disabled.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
}

impl GenerateServiceAccountKey201ResponseKey {
    /// A key for service account authentication. Keys are used to generate JWTs for authenticating as the service account.
    pub fn new(
        name: String,
        key_id: String,
        key_algorithm: KeyAlgorithm,
        valid_after_time: String,
    ) -> GenerateServiceAccountKey201ResponseKey {
        GenerateServiceAccountKey201ResponseKey {
            name,
            key_id,
            key_algorithm,
            key_origin: None,
            valid_after_time,
            valid_before_time: None,
            disabled: None,
        }
    }
}
/// The algorithm used for the key pair.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyAlgorithm {
    #[serde(rename = "RSA_2048")]
    Rsa2048,
    #[serde(rename = "RSA_4096")]
    Rsa4096,
    #[serde(rename = "EC_P256")]
    EcP256,
    #[serde(rename = "EC_P384")]
    EcP384,
}

impl Default for KeyAlgorithm {
    fn default() -> KeyAlgorithm {
        Self::Rsa2048
    }
}
/// How the key was created.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyOrigin {
    #[serde(rename = "SYSTEM_PROVIDED")]
    SystemProvided,
    #[serde(rename = "USER_PROVIDED")]
    UserProvided,
}

impl Default for KeyOrigin {
    fn default() -> KeyOrigin {
        Self::SystemProvided
    }
}
