/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200ResponseUsageApiCalls : API call counts by category.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200ResponseUsageApiCalls {
    /// Number of Admin API calls.
    #[serde(rename = "adminApi", skip_serializing_if = "Option::is_none")]
    pub admin_api: Option<i64>,
    /// Number of Public API calls.
    #[serde(rename = "publicApi", skip_serializing_if = "Option::is_none")]
    pub public_api: Option<i64>,
}

impl GetProjectUsage200ResponseUsageApiCalls {
    /// API call counts by category.
    pub fn new() -> GetProjectUsage200ResponseUsageApiCalls {
        GetProjectUsage200ResponseUsageApiCalls {
            admin_api: None,
            public_api: None,
        }
    }
}
