/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetServiceAccount200Response : Response containing the requested service account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServiceAccount200Response {
    #[serde(rename = "serviceAccount", skip_serializing_if = "Option::is_none")]
    pub service_account: Option<Box<models::ListServiceAccounts200ResponseServiceAccountsInner>>,
}

impl GetServiceAccount200Response {
    /// Response containing the requested service account.
    pub fn new() -> GetServiceAccount200Response {
        GetServiceAccount200Response {
            service_account: None,
        }
    }
}
