/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectQuotas200ResponseQuotas : Quota limits and current usage for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectQuotas200ResponseQuotas {
    /// Resource name in the format \"projects/{project_id}/quotas\"
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "serviceAccounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "tenants", skip_serializing_if = "Option::is_none")]
    pub tenants: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "apiKeysPerApp", skip_serializing_if = "Option::is_none")]
    pub api_keys_per_app: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "requestsPerMinute", skip_serializing_if = "Option::is_none")]
    pub requests_per_minute: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
    #[serde(rename = "requestsPerDay", skip_serializing_if = "Option::is_none")]
    pub requests_per_day: Option<Box<models::GetProjectQuotas200ResponseQuotasUsers>>,
}

impl GetProjectQuotas200ResponseQuotas {
    /// Quota limits and current usage for a project.
    pub fn new() -> GetProjectQuotas200ResponseQuotas {
        GetProjectQuotas200ResponseQuotas {
            name: None,
            users: None,
            service_accounts: None,
            tenants: None,
            apps: None,
            api_keys_per_app: None,
            requests_per_minute: None,
            requests_per_day: None,
        }
    }
}
