/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200ResponseUsagePeriod : The time period for the usage data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200ResponseUsagePeriod {
    /// Start of the period.
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// End of the period.
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
}

impl GetProjectUsage200ResponseUsagePeriod {
    /// The time period for the usage data.
    pub fn new() -> GetProjectUsage200ResponseUsagePeriod {
        GetProjectUsage200ResponseUsagePeriod {
            start_time: None,
            end_time: None,
        }
    }
}
