/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetTenant200Response : Response containing the requested tenant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTenant200Response {
    #[serde(rename = "tenant", skip_serializing_if = "Option::is_none")]
    pub tenant: Option<Box<models::ListTenants200ResponseTenantsInner>>,
}

impl GetTenant200Response {
    /// Response containing the requested tenant.
    pub fn new() -> GetTenant200Response {
        GetTenant200Response { tenant: None }
    }
}
