/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectQuotas200ResponseQuotasUsers : A quota limit with current usage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectQuotas200ResponseQuotasUsers {
    /// The maximum allowed value. -1 indicates unlimited.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Current usage against this quota.
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<i64>,
    /// Unit of measurement.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl GetProjectQuotas200ResponseQuotasUsers {
    /// A quota limit with current usage.
    pub fn new() -> GetProjectQuotas200ResponseQuotasUsers {
        GetProjectQuotas200ResponseQuotasUsers {
            limit: None,
            current: None,
            unit: None,
        }
    }
}
