/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetAppConfig200Response : Response containing SDK configuration for the app. The format depends on the platform: - iOS: GoogleService-Info.plist (XML plist format) - Android: google-services.json (JSON format) - macOS/Windows/Linux: pistachio-config.json (JSON format) - Web: JavaScript config object (JSON format)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAppConfig200Response {
    /// Contents of the platform-specific config file.
    #[serde(rename = "configFileContents", skip_serializing_if = "Option::is_none")]
    pub config_file_contents: Option<String>,
    /// Recommended filename for the config file.
    #[serde(rename = "configFilename", skip_serializing_if = "Option::is_none")]
    pub config_filename: Option<String>,
}

impl GetAppConfig200Response {
    /// Response containing SDK configuration for the app. The format depends on the platform: - iOS: GoogleService-Info.plist (XML plist format) - Android: google-services.json (JSON format) - macOS/Windows/Linux: pistachio-config.json (JSON format) - Web: JavaScript config object (JSON format)
    pub fn new() -> GetAppConfig200Response {
        GetAppConfig200Response {
            config_file_contents: None,
            config_filename: None,
        }
    }
}
