/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetApiKey200Response : Response containing the requested API key metadata. For security, only the masked key prefix is returned. The full key string is only available at creation time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKey200Response {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Box<models::ListApiKeys200ResponseApiKeysInner>>,
}

impl GetApiKey200Response {
    /// Response containing the requested API key metadata. For security, only the masked key prefix is returned. The full key string is only available at creation time.
    pub fn new() -> GetApiKey200Response {
        GetApiKey200Response { api_key: None }
    }
}
