/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200ResponseUsage : Usage statistics for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200ResponseUsage {
    /// Resource name in the format \"projects/{project_id}/usage\"
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<Box<models::GetProjectUsage200ResponseUsagePeriod>>,
    #[serde(rename = "activeUsers", skip_serializing_if = "Option::is_none")]
    pub active_users: Option<Box<models::GetProjectUsage200ResponseUsageActiveUsers>>,
    #[serde(rename = "authentications", skip_serializing_if = "Option::is_none")]
    pub authentications: Option<Box<models::GetProjectUsage200ResponseUsageAuthentications>>,
    #[serde(rename = "apiCalls", skip_serializing_if = "Option::is_none")]
    pub api_calls: Option<Box<models::GetProjectUsage200ResponseUsageApiCalls>>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Box<models::GetProjectUsage200ResponseUsageStorage>>,
}

impl GetProjectUsage200ResponseUsage {
    /// Usage statistics for a project.
    pub fn new() -> GetProjectUsage200ResponseUsage {
        GetProjectUsage200ResponseUsage {
            name: None,
            period: None,
            active_users: None,
            authentications: None,
            api_calls: None,
            storage: None,
        }
    }
}
