/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200ResponseUsageAuthentications : Authentication event counts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200ResponseUsageAuthentications {
    /// Number of new user signups.
    #[serde(rename = "signups", skip_serializing_if = "Option::is_none")]
    pub signups: Option<i64>,
    /// Number of successful logins.
    #[serde(rename = "logins", skip_serializing_if = "Option::is_none")]
    pub logins: Option<i64>,
    /// Number of token refreshes.
    #[serde(rename = "tokenRefreshes", skip_serializing_if = "Option::is_none")]
    pub token_refreshes: Option<i64>,
    /// Number of failed authentication attempts.
    #[serde(rename = "failedAttempts", skip_serializing_if = "Option::is_none")]
    pub failed_attempts: Option<i64>,
}

impl GetProjectUsage200ResponseUsageAuthentications {
    /// Authentication event counts.
    pub fn new() -> GetProjectUsage200ResponseUsageAuthentications {
        GetProjectUsage200ResponseUsageAuthentications {
            signups: None,
            logins: None,
            token_refreshes: None,
            failed_attempts: None,
        }
    }
}
