/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUser200Response : Response containing the requested user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUser200Response {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::CreateProjectUser201ResponseUser>>,
}

impl GetProjectUser200Response {
    /// Response containing the requested user.
    pub fn new() -> GetProjectUser200Response {
        GetProjectUser200Response { user: None }
    }
}
