/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200ResponseUsageStorage : Storage usage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200ResponseUsageStorage {
    /// Total number of users.
    #[serde(rename = "totalUsers", skip_serializing_if = "Option::is_none")]
    pub total_users: Option<i64>,
    /// Total number of service accounts.
    #[serde(
        rename = "totalServiceAccounts",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_service_accounts: Option<i64>,
    /// Total number of tenants.
    #[serde(rename = "totalTenants", skip_serializing_if = "Option::is_none")]
    pub total_tenants: Option<i64>,
    /// Total number of apps.
    #[serde(rename = "totalApps", skip_serializing_if = "Option::is_none")]
    pub total_apps: Option<i64>,
}

impl GetProjectUsage200ResponseUsageStorage {
    /// Storage usage.
    pub fn new() -> GetProjectUsage200ResponseUsageStorage {
        GetProjectUsage200ResponseUsageStorage {
            total_users: None,
            total_service_accounts: None,
            total_tenants: None,
            total_apps: None,
        }
    }
}
