/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetAdminSdkConfig200Response : Response containing the Admin SDK configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAdminSdkConfig200Response {
    /// The project ID.
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Storage bucket name.
    #[serde(rename = "storageBucket", skip_serializing_if = "Option::is_none")]
    pub storage_bucket: Option<String>,
    /// Location/region for default resources.
    #[serde(rename = "locationId", skip_serializing_if = "Option::is_none")]
    pub location_id: Option<String>,
}

impl GetAdminSdkConfig200Response {
    /// Response containing the Admin SDK configuration.
    pub fn new() -> GetAdminSdkConfig200Response {
        GetAdminSdkConfig200Response {
            project_id: None,
            storage_bucket: None,
            location_id: None,
        }
    }
}
