/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectAuthProvider200Response : Response containing a single project auth provider.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectAuthProvider200Response {
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInner>>,
}

impl GetProjectAuthProvider200Response {
    /// Response containing a single project auth provider.
    pub fn new() -> GetProjectAuthProvider200Response {
        GetProjectAuthProvider200Response { provider: None }
    }
}
