/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectUsage200Response : Response containing project usage statistics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectUsage200Response {
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::GetProjectUsage200ResponseUsage>>,
}

impl GetProjectUsage200Response {
    /// Response containing project usage statistics.
    pub fn new() -> GetProjectUsage200Response {
        GetProjectUsage200Response { usage: None }
    }
}
