/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetEffectiveTenantAuthProviders200ResponseProvidersInner : The effective auth provider configuration after merging project and tenant configurations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEffectiveTenantAuthProviders200ResponseProvidersInner {
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInner>>,
    /// Indicates where the effective configuration originates.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
}

impl GetEffectiveTenantAuthProviders200ResponseProvidersInner {
    /// The effective auth provider configuration after merging project and tenant configurations.
    pub fn new() -> GetEffectiveTenantAuthProviders200ResponseProvidersInner {
        GetEffectiveTenantAuthProviders200ResponseProvidersInner {
            provider: None,
            source: None,
        }
    }
}
/// Indicates where the effective configuration originates.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "PROJECT")]
    Project,
    #[serde(rename = "TENANT")]
    Tenant,
}

impl Default for Source {
    fn default() -> Source {
        Self::Project
    }
}
