/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// GetProjectQuotas200Response : Response containing project quotas.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProjectQuotas200Response {
    #[serde(rename = "quotas", skip_serializing_if = "Option::is_none")]
    pub quotas: Option<Box<models::GetProjectQuotas200ResponseQuotas>>,
}

impl GetProjectQuotas200Response {
    /// Response containing project quotas.
    pub fn new() -> GetProjectQuotas200Response {
        GetProjectQuotas200Response { quotas: None }
    }
}
