/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ImportProjectUsersRequest : Request body for batch importing users. Allows bulk import of users from external systems with optional password hash migration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportProjectUsersRequest {
    /// List of users to import. Maximum 1000 users per request.
    #[serde(rename = "users")]
    pub users: Vec<models::ImportProjectUsersRequestUsersInner>,
    /// The algorithm used for password hashes during import.
    #[serde(rename = "hashAlgorithm", skip_serializing_if = "Option::is_none")]
    pub hash_algorithm: Option<HashAlgorithm>,
    #[serde(rename = "hashConfig", skip_serializing_if = "Option::is_none")]
    pub hash_config: Option<Box<models::ImportProjectUsersRequestHashConfig>>,
}

impl ImportProjectUsersRequest {
    /// Request body for batch importing users. Allows bulk import of users from external systems with optional password hash migration.
    pub fn new(
        users: Vec<models::ImportProjectUsersRequestUsersInner>,
    ) -> ImportProjectUsersRequest {
        ImportProjectUsersRequest {
            users,
            hash_algorithm: None,
            hash_config: None,
        }
    }
}
/// The algorithm used for password hashes during import.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HashAlgorithm {
    #[serde(rename = "SCRYPT")]
    Scrypt,
    #[serde(rename = "BCRYPT")]
    Bcrypt,
    #[serde(rename = "ARGON2")]
    Argon2,
    #[serde(rename = "PBKDF2_SHA256")]
    Pbkdf2Sha256,
}

impl Default for HashAlgorithm {
    fn default() -> HashAlgorithm {
        Self::Scrypt
    }
}
