/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ImportProjectUsersRequestUsersInner : A user record for batch import. Used with the ImportUsers endpoint to bulk import users from external systems.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportProjectUsersRequestUsersInner {
    /// User's primary email address.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the email has been verified.
    #[serde(rename = "emailVerified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    /// User's phone number in E.164 format.
    #[serde(
        rename = "phoneNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// Human-readable display name.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// URL to the user's profile photo.
    #[serde(
        rename = "photoUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub photo_url: Option<Option<String>>,
    /// Whether the account is disabled.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Custom claims for the ID token.
    #[serde(rename = "customClaims", skip_serializing_if = "Option::is_none")]
    pub custom_claims: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Base64-encoded password hash for PDPKA import. Format depends on hashAlgorithm in the import request.
    #[serde(
        rename = "passwordHash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password_hash: Option<Option<String>>,
    /// Base64-encoded salt used with the password hash.
    #[serde(
        rename = "passwordSalt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password_salt: Option<Option<String>>,
}

impl ImportProjectUsersRequestUsersInner {
    /// A user record for batch import. Used with the ImportUsers endpoint to bulk import users from external systems.
    pub fn new() -> ImportProjectUsersRequestUsersInner {
        ImportProjectUsersRequestUsersInner {
            email: None,
            email_verified: None,
            phone_number: None,
            display_name: None,
            photo_url: None,
            disabled: None,
            custom_claims: None,
            password_hash: None,
            password_salt: None,
        }
    }
}
