/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ImportProjectUsers200Response : Response containing import results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportProjectUsers200Response {
    /// Number of users successfully imported.
    #[serde(rename = "successCount", skip_serializing_if = "Option::is_none")]
    pub success_count: Option<i32>,
    /// Number of users that failed to import.
    #[serde(rename = "failureCount", skip_serializing_if = "Option::is_none")]
    pub failure_count: Option<i32>,
    /// Details about failed imports.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::ImportProjectUsers200ResponseErrorsInner>>,
}

impl ImportProjectUsers200Response {
    /// Response containing import results.
    pub fn new() -> ImportProjectUsers200Response {
        ImportProjectUsers200Response {
            success_count: None,
            failure_count: None,
            errors: None,
        }
    }
}
