/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ImportProjectUsers200ResponseErrorsInner : Details about a failed user import.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportProjectUsers200ResponseErrorsInner {
    /// Zero-based index of the user in the request array.
    #[serde(rename = "index")]
    pub index: i32,
    /// Error message describing the failure.
    #[serde(rename = "message")]
    pub message: String,
    /// Field that caused the error, if applicable.
    #[serde(
        rename = "field",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub field: Option<Option<String>>,
}

impl ImportProjectUsers200ResponseErrorsInner {
    /// Details about a failed user import.
    pub fn new(index: i32, message: String) -> ImportProjectUsers200ResponseErrorsInner {
        ImportProjectUsers200ResponseErrorsInner {
            index,
            message,
            field: None,
        }
    }
}
