/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ImportProjectUsersRequestHashConfig : Algorithm-specific configuration for password hashing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportProjectUsersRequestHashConfig {
    /// Number of rounds for BCRYPT/SCRYPT.
    #[serde(
        rename = "rounds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rounds: Option<Option<i32>>,
    /// Memory cost parameter for SCRYPT/ARGON2.
    #[serde(
        rename = "memoryCost",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub memory_cost: Option<Option<i32>>,
    /// Parallelization parameter for SCRYPT/ARGON2.
    #[serde(
        rename = "parallelization",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parallelization: Option<Option<i32>>,
    /// Base64-encoded salt separator for SCRYPT.
    #[serde(
        rename = "saltSeparator",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub salt_separator: Option<Option<String>>,
    /// Base64-encoded signer key for SCRYPT.
    #[serde(
        rename = "signerKey",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub signer_key: Option<Option<String>>,
}

impl ImportProjectUsersRequestHashConfig {
    /// Algorithm-specific configuration for password hashing.
    pub fn new() -> ImportProjectUsersRequestHashConfig {
        ImportProjectUsersRequestHashConfig {
            rounds: None,
            memory_cost: None,
            parallelization: None,
            salt_separator: None,
            signer_key: None,
        }
    }
}
