/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectUsers200ResponseUsersInner : A user account within a project or tenant. Users are the identity records for authentication. Each user has a system-generated pistachio_id as their unique identifier.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectUsers200ResponseUsersInner {
    /// Resource name in the format: - Project users: \"projects/{project_id}/users/{pistachio_id}\" - Tenant users: \"projects/{project_id}/tenants/{tenant_id}/users/{pistachio_id}\"
    #[serde(rename = "name")]
    pub name: String,
    /// System-generated user identifier. 16 bytes encoded as 32 hex characters ending in '00'.
    #[serde(rename = "pistachioId")]
    pub pistachio_id: String,
    /// Tenant ID this user belongs to. Null for project-level users (single-tenant mode).
    #[serde(
        rename = "tenantId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenant_id: Option<Option<String>>,
    /// User's primary email address. Unique within the project/tenant scope if set.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the user's email address has been verified.
    #[serde(rename = "emailVerified")]
    pub email_verified: bool,
    /// User's phone number in E.164 format (e.g., \"+14155551234\"). Unique within the project/tenant scope if set.
    #[serde(
        rename = "phoneNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// Human-readable display name for the user. Max 256 characters.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// URL to the user's profile photo.
    #[serde(
        rename = "photoUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub photo_url: Option<Option<String>>,
    /// Whether the user account is disabled. Disabled users cannot sign in.
    #[serde(rename = "disabled")]
    pub disabled: bool,
    /// Custom claims to include in the user's ID token. Used for application-specific authorization. Maximum size: 1000 bytes when JSON-encoded.
    #[serde(rename = "customClaims", skip_serializing_if = "Option::is_none")]
    pub custom_claims: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Timestamp when the user account was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Timestamp when the user last signed in.
    #[serde(
        rename = "lastSignInAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_sign_in_at: Option<Option<String>>,
    /// Timestamp when the user's tokens were last refreshed.
    #[serde(
        rename = "lastRefreshAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_refresh_at: Option<Option<String>>,
    /// Timestamp when the user account was last updated.
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ListProjectUsers200ResponseUsersInner {
    /// A user account within a project or tenant. Users are the identity records for authentication. Each user has a system-generated pistachio_id as their unique identifier.
    pub fn new(
        name: String,
        pistachio_id: String,
        email_verified: bool,
        disabled: bool,
        created_at: String,
        updated_at: String,
    ) -> ListProjectUsers200ResponseUsersInner {
        ListProjectUsers200ResponseUsersInner {
            name,
            pistachio_id,
            tenant_id: None,
            email: None,
            email_verified,
            phone_number: None,
            display_name: None,
            photo_url: None,
            disabled,
            custom_claims: None,
            created_at,
            last_sign_in_at: None,
            last_refresh_at: None,
            updated_at,
        }
    }
}
