/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjects400Response : Standard error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects400Response {
    /// Machine-readable error code
    #[serde(rename = "code")]
    pub code: String,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
}

impl ListProjects400Response {
    /// Standard error response
    pub fn new(code: String, message: String) -> ListProjects400Response {
        ListProjects400Response { code, message }
    }
}
