/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListTenants200ResponseTenantsInner : Multi-tenant isolation within a project. Tenants provide isolated user pools for B2B SaaS applications where each customer needs their own authentication configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTenants200ResponseTenantsInner {
    /// Resource name in the format \"projects/{project_id}/tenants/{tenant_id}\".
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unique tenant identifier within the project. Immutable after creation. Case-sensitive, 1-128 characters, alphanumeric with underscores.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Internal tenant identifier. 16 bytes encoded as 32 hex characters ending in '02'.
    #[serde(rename = "pistachioId", skip_serializing_if = "Option::is_none")]
    pub pistachio_id: Option<String>,
    /// Human-readable display name. Max 256 characters.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether passphrase-derived public key authentication (PDPKA) sign-up is allowed. When true, users can register using passphrase-derived keypairs.
    #[serde(rename = "allowPdpkaSignup", skip_serializing_if = "Option::is_none")]
    pub allow_pdpka_signup: Option<bool>,
    /// Whether all authentication is disabled for this tenant. When true, users cannot sign in to this tenant.
    #[serde(rename = "disableAuth", skip_serializing_if = "Option::is_none")]
    pub disable_auth: Option<bool>,
    /// Enabled MFA providers for this tenant. Valid values: \"phone\", \"totp\"
    #[serde(rename = "mfaConfig", skip_serializing_if = "Option::is_none")]
    pub mfa_config: Option<Vec<MfaConfig>>,
    /// Timestamp when the tenant was created.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the tenant was last updated.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ListTenants200ResponseTenantsInner {
    /// Multi-tenant isolation within a project. Tenants provide isolated user pools for B2B SaaS applications where each customer needs their own authentication configuration.
    pub fn new() -> ListTenants200ResponseTenantsInner {
        ListTenants200ResponseTenantsInner {
            name: None,
            tenant_id: None,
            pistachio_id: None,
            display_name: None,
            allow_pdpka_signup: None,
            disable_auth: None,
            mfa_config: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// Enabled MFA providers for this tenant. Valid values: \"phone\", \"totp\"
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaConfig {
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "totp")]
    Totp,
}

impl Default for MfaConfig {
    fn default() -> MfaConfig {
        Self::Phone
    }
}
