/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectUserMfaFactors200ResponseFactorsInner : A multi-factor authentication factor enrolled by a user. Factors can be TOTP (time-based one-time password), SMS, or email.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectUserMfaFactors200ResponseFactorsInner {
    /// Unique factor identifier.
    #[serde(rename = "factorId")]
    pub factor_id: String,
    /// The type of MFA factor.
    #[serde(rename = "factorType")]
    pub factor_type: FactorType,
    /// User-provided name for the factor.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// Phone number for SMS factor (E.164 format).
    #[serde(
        rename = "phoneNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// Email address for email factor.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the factor has been verified.
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    /// Timestamp when the factor was enrolled.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Timestamp when the factor was last used.
    #[serde(
        rename = "lastUsedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_used_at: Option<Option<String>>,
}

impl ListProjectUserMfaFactors200ResponseFactorsInner {
    /// A multi-factor authentication factor enrolled by a user. Factors can be TOTP (time-based one-time password), SMS, or email.
    pub fn new(
        factor_id: String,
        factor_type: FactorType,
        created_at: String,
    ) -> ListProjectUserMfaFactors200ResponseFactorsInner {
        ListProjectUserMfaFactors200ResponseFactorsInner {
            factor_id,
            factor_type,
            display_name: None,
            phone_number: None,
            email: None,
            verified: None,
            created_at,
            last_used_at: None,
        }
    }
}
/// The type of MFA factor.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FactorType {
    #[serde(rename = "TOTP")]
    Totp,
    #[serde(rename = "SMS")]
    Sms,
    #[serde(rename = "EMAIL")]
    Email,
}

impl Default for FactorType {
    fn default() -> FactorType {
        Self::Totp
    }
}
