/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjects200ResponseProjectsInnerResources : Default resources provisioned for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects200ResponseProjectsInnerResources {
    /// Default hosting site name.
    #[serde(rename = "hostingSite", skip_serializing_if = "Option::is_none")]
    pub hosting_site: Option<String>,
    /// Default realtime database instance name.
    #[serde(
        rename = "realtimeDatabaseInstance",
        skip_serializing_if = "Option::is_none"
    )]
    pub realtime_database_instance: Option<String>,
    /// Default storage bucket.
    #[serde(rename = "storageBucket", skip_serializing_if = "Option::is_none")]
    pub storage_bucket: Option<String>,
}

impl ListProjects200ResponseProjectsInnerResources {
    /// Default resources provisioned for a project.
    pub fn new() -> ListProjects200ResponseProjectsInnerResources {
        ListProjects200ResponseProjectsInnerResources {
            hosting_site: None,
            realtime_database_instance: None,
            storage_bucket: None,
        }
    }
}
