/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApps200ResponseAppsInnerWeb : Web-specific app configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApps200ResponseAppsInnerWeb {
    /// Authorized domains for OAuth redirects and CORS.
    #[serde(rename = "authorizedDomains", skip_serializing_if = "Option::is_none")]
    pub authorized_domains: Option<Vec<String>>,
    /// Auth domain for this app (e.g., \"myapp.pistachiohq.com\").
    #[serde(rename = "authDomain", skip_serializing_if = "Option::is_none")]
    pub auth_domain: Option<String>,
}

impl ListApps200ResponseAppsInnerWeb {
    /// Web-specific app configuration.
    pub fn new() -> ListApps200ResponseAppsInnerWeb {
        ListApps200ResponseAppsInnerWeb {
            authorized_domains: None,
            auth_domain: None,
        }
    }
}
