/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectAuthProviders200ResponseProvidersInnerOidc : Configuration for generic OpenID Connect providers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectAuthProviders200ResponseProvidersInnerOidc {
    /// Human-readable name for the provider shown in the sign-in UI.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The OIDC issuer URL (must support discovery).
    #[serde(rename = "issuerUrl", skip_serializing_if = "Option::is_none")]
    pub issuer_url: Option<String>,
    /// OIDC client ID.
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// OIDC scopes to request.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    /// Additional parameters to include in authorization requests.
    #[serde(rename = "additionalParams", skip_serializing_if = "Option::is_none")]
    pub additional_params: Option<std::collections::HashMap<String, String>>,
}

impl ListProjectAuthProviders200ResponseProvidersInnerOidc {
    /// Configuration for generic OpenID Connect providers.
    pub fn new() -> ListProjectAuthProviders200ResponseProvidersInnerOidc {
        ListProjectAuthProviders200ResponseProvidersInnerOidc {
            display_name: None,
            issuer_url: None,
            client_id: None,
            scopes: None,
            additional_params: None,
        }
    }
}
