/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner : An Android application identified by package name and SHA-256 fingerprint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner
{
    /// The Android package name.
    #[serde(rename = "packageName", skip_serializing_if = "Option::is_none")]
    pub package_name: Option<String>,
    /// SHA-256 fingerprint of the signing certificate.
    #[serde(
        rename = "sha256CertFingerprint",
        skip_serializing_if = "Option::is_none"
    )]
    pub sha256_cert_fingerprint: Option<String>,
}

impl ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner {
    /// An Android application identified by package name and SHA-256 fingerprint.
    pub fn new()
    -> ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner
    {
        ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner {
            package_name: None,
            sha256_cert_fingerprint: None,
        }
    }
}
