/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListTenants200ResponsePagination : Pagination metadata for list and search responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTenants200ResponsePagination {
    /// Cursor for fetching the next page of results. Pass this value as the `cursor` parameter in the next request. When `nextCursor` equals the input `cursor`, there are no more results.
    #[serde(rename = "nextCursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Total number of items matching the request. May be omitted for performance reasons on large result sets.
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
}

impl ListTenants200ResponsePagination {
    /// Pagination metadata for list and search responses.
    pub fn new() -> ListTenants200ResponsePagination {
        ListTenants200ResponsePagination {
            next_cursor: None,
            total_count: None,
        }
    }
}
