/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectAuthProviders200Response : Response containing the list of project auth providers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectAuthProviders200Response {
    /// List of configured auth providers, ordered by displayOrder.
    #[serde(rename = "providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<Vec<models::ListProjectAuthProviders200ResponseProvidersInner>>,
}

impl ListProjectAuthProviders200Response {
    /// Response containing the list of project auth providers.
    pub fn new() -> ListProjectAuthProviders200Response {
        ListProjectAuthProviders200Response { providers: None }
    }
}
