/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListTenantUsers200Response : Response containing a page of users.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTenantUsers200Response {
    /// The list of users.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::CreateProjectUser201ResponseUser>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListTenants200ResponsePagination>>,
}

impl ListTenantUsers200Response {
    /// Response containing a page of users.
    pub fn new() -> ListTenantUsers200Response {
        ListTenantUsers200Response {
            users: None,
            pagination: None,
        }
    }
}
