/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectAuthProviders200ResponseProvidersInner : An authentication provider configured at the project level. Providers define how users can authenticate to the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectAuthProviders200ResponseProvidersInner {
    /// Provider identifier. Built-in providers: \"pdpka\", \"anonymous\", \"google\", \"apple\". Custom OIDC providers use the format \"oidc:<name>\", e.g., \"oidc:okta\".
    #[serde(rename = "providerId", skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    /// Whether this provider is enabled for authentication.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Display order in sign-in UI. Lower values appear first.
    #[serde(rename = "displayOrder", skip_serializing_if = "Option::is_none")]
    pub display_order: Option<i32>,
    #[serde(rename = "pdpka", skip_serializing_if = "Option::is_none")]
    pub pdpka: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerPdpka>>,
    #[serde(rename = "anonymous", skip_serializing_if = "Option::is_none")]
    pub anonymous: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerAnonymous>>,
    #[serde(rename = "oauth", skip_serializing_if = "Option::is_none")]
    pub oauth: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerOauth>>,
    #[serde(rename = "oidc", skip_serializing_if = "Option::is_none")]
    pub oidc: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerOidc>>,
    /// Timestamp when the provider was configured.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the provider was last updated.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ListProjectAuthProviders200ResponseProvidersInner {
    /// An authentication provider configured at the project level. Providers define how users can authenticate to the project.
    pub fn new() -> ListProjectAuthProviders200ResponseProvidersInner {
        ListProjectAuthProviders200ResponseProvidersInner {
            provider_id: None,
            enabled: None,
            display_order: None,
            pdpka: None,
            anonymous: None,
            oauth: None,
            oidc: None,
            created_at: None,
            updated_at: None,
        }
    }
}
