/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApps200ResponseAppsInnerMacos : macOS-specific app configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApps200ResponseAppsInnerMacos {
    /// macOS bundle identifier (e.g., \"com.example.myapp\").
    #[serde(rename = "bundleId")]
    pub bundle_id: String,
    /// Apple Team ID for code signing verification.
    #[serde(rename = "teamId", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<String>,
    /// Mac App Store ID. Optional.
    #[serde(rename = "macAppStoreId", skip_serializing_if = "Option::is_none")]
    pub mac_app_store_id: Option<String>,
}

impl ListApps200ResponseAppsInnerMacos {
    /// macOS-specific app configuration.
    pub fn new(bundle_id: String) -> ListApps200ResponseAppsInnerMacos {
        ListApps200ResponseAppsInnerMacos {
            bundle_id,
            team_id: None,
            mac_app_store_id: None,
        }
    }
}
