/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApiKeys200ResponseApiKeysInner : API key metadata with masked key value. For security, the full key string is only available at creation time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeys200ResponseApiKeysInner {
    /// Resource name in the format: \"projects/{project_id}/apps/{app_id}/apiKeys/{key_id}\"
    #[serde(rename = "name")]
    pub name: String,
    /// Unique key identifier.
    #[serde(rename = "keyId")]
    pub key_id: String,
    /// Masked prefix of the API key for identification purposes. The full key is only available at creation time.
    #[serde(rename = "keyPrefix")]
    pub key_prefix: String,
    /// Human-readable display name for the key.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(rename = "restrictions", skip_serializing_if = "Option::is_none")]
    pub restrictions: Option<Box<models::ListApiKeys200ResponseApiKeysInnerRestrictions>>,
    /// Timestamp when the key was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Timestamp when the key was last updated.
    #[serde(
        rename = "updatedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
}

impl ListApiKeys200ResponseApiKeysInner {
    /// API key metadata with masked key value. For security, the full key string is only available at creation time.
    pub fn new(
        name: String,
        key_id: String,
        key_prefix: String,
        created_at: String,
    ) -> ListApiKeys200ResponseApiKeysInner {
        ListApiKeys200ResponseApiKeysInner {
            name,
            key_id,
            key_prefix,
            display_name: None,
            restrictions: None,
            created_at,
            updated_at: None,
        }
    }
}
