/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApps200ResponseAppsInnerLinux : Linux-specific app configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApps200ResponseAppsInnerLinux {
    /// Application name for identification.
    #[serde(rename = "appName")]
    pub app_name: String,
    /// Flatpak app ID (e.g., \"com.example.App\"). Optional.
    #[serde(rename = "flatpakId", skip_serializing_if = "Option::is_none")]
    pub flatpak_id: Option<String>,
    /// Snap package name. Optional.
    #[serde(rename = "snapName", skip_serializing_if = "Option::is_none")]
    pub snap_name: Option<String>,
}

impl ListApps200ResponseAppsInnerLinux {
    /// Linux-specific app configuration.
    pub fn new(app_name: String) -> ListApps200ResponseAppsInnerLinux {
        ListApps200ResponseAppsInnerLinux {
            app_name,
            flatpak_id: None,
            snap_name: None,
        }
    }
}
