/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListServiceAccountKeys200Response : Response containing the service account's keys.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServiceAccountKeys200Response {
    /// The list of keys for the service account.
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Vec<models::ListServiceAccountKeys200ResponseKeysInner>>,
}

impl ListServiceAccountKeys200Response {
    /// Response containing the service account's keys.
    pub fn new() -> ListServiceAccountKeys200Response {
        ListServiceAccountKeys200Response { keys: None }
    }
}
