/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectAuthProviders200ResponseProvidersInnerAnonymous : Configuration for anonymous authentication. Anonymous auth creates temporary user sessions without requiring credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectAuthProviders200ResponseProvidersInnerAnonymous {
    /// Duration in seconds for anonymous sessions.
    #[serde(
        rename = "sessionDurationSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_duration_seconds: Option<i32>,
    /// Whether to automatically upgrade anonymous users to permanent accounts when they link credentials.
    #[serde(rename = "autoUpgrade", skip_serializing_if = "Option::is_none")]
    pub auto_upgrade: Option<bool>,
}

impl ListProjectAuthProviders200ResponseProvidersInnerAnonymous {
    /// Configuration for anonymous authentication. Anonymous auth creates temporary user sessions without requiring credentials.
    pub fn new() -> ListProjectAuthProviders200ResponseProvidersInnerAnonymous {
        ListProjectAuthProviders200ResponseProvidersInnerAnonymous {
            session_duration_seconds: None,
            auto_upgrade: None,
        }
    }
}
