/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApps200ResponseAppsInner : A registered application for any platform. Apps are platform-specific client applications within a project. Each app targets a specific platform and shares the project's user pool.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApps200ResponseAppsInner {
    /// Resource name in the format \"projects/{project_id}/apps/{app_id}\".
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Globally unique app identifier assigned by the system.
    #[serde(rename = "appId", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    /// Internal app identifier. 16 bytes encoded as 32 hex characters ending in '03'.
    #[serde(rename = "pistachioId", skip_serializing_if = "Option::is_none")]
    pub pistachio_id: Option<String>,
    /// Human-readable display name for the app.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The project this app belongs to.
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// Target platform for an app.
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<Platform>,
    /// Auto-generated API key for this app. Only returned on app creation.
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Lifecycle state of an app.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "ios", skip_serializing_if = "Option::is_none")]
    pub ios: Option<Box<models::ListApps200ResponseAppsInnerIos>>,
    #[serde(rename = "android", skip_serializing_if = "Option::is_none")]
    pub android: Option<Box<models::ListApps200ResponseAppsInnerAndroid>>,
    #[serde(rename = "macos", skip_serializing_if = "Option::is_none")]
    pub macos: Option<Box<models::ListApps200ResponseAppsInnerMacos>>,
    #[serde(rename = "windows", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<models::ListApps200ResponseAppsInnerWindows>>,
    #[serde(rename = "linux", skip_serializing_if = "Option::is_none")]
    pub linux: Option<Box<models::ListApps200ResponseAppsInnerLinux>>,
    #[serde(rename = "web", skip_serializing_if = "Option::is_none")]
    pub web: Option<Box<models::ListApps200ResponseAppsInnerWeb>>,
    /// Timestamp when the app was created.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the app was last updated.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ListApps200ResponseAppsInner {
    /// A registered application for any platform. Apps are platform-specific client applications within a project. Each app targets a specific platform and shares the project's user pool.
    pub fn new() -> ListApps200ResponseAppsInner {
        ListApps200ResponseAppsInner {
            name: None,
            app_id: None,
            pistachio_id: None,
            display_name: None,
            project_id: None,
            platform: None,
            api_key: None,
            state: None,
            ios: None,
            android: None,
            macos: None,
            windows: None,
            linux: None,
            web: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// Target platform for an app.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "IOS")]
    Ios,
    #[serde(rename = "ANDROID")]
    Android,
    #[serde(rename = "MACOS")]
    Macos,
    #[serde(rename = "WINDOWS")]
    Windows,
    #[serde(rename = "LINUX")]
    Linux,
    #[serde(rename = "WEB")]
    Web,
}

impl Default for Platform {
    fn default() -> Platform {
        Self::Ios
    }
}
/// Lifecycle state of an app.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DELETED")]
    Deleted,
}

impl Default for State {
    fn default() -> State {
        Self::Active
    }
}
