/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictions : Restrictions for Android API keys.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictions {
    /// List of allowed Android applications.
    #[serde(rename = "allowedApplications", skip_serializing_if = "Option::is_none")]
    pub allowed_applications: Option<Vec<models::ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictionsAllowedApplicationsInner>>,
}

impl ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictions {
    /// Restrictions for Android API keys.
    pub fn new() -> ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictions {
        ListApiKeys200ResponseApiKeysInnerRestrictionsAndroidKeyRestrictions {
            allowed_applications: None,
        }
    }
}
