/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListServiceAccounts200Response : Response containing a page of service accounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServiceAccounts200Response {
    /// The list of service accounts.
    #[serde(rename = "serviceAccounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<Vec<models::ListServiceAccounts200ResponseServiceAccountsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListProjects200ResponsePagination>>,
}

impl ListServiceAccounts200Response {
    /// Response containing a page of service accounts.
    pub fn new() -> ListServiceAccounts200Response {
        ListServiceAccounts200Response {
            service_accounts: None,
            pagination: None,
        }
    }
}
