/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApps200ResponseAppsInnerAndroid : Android-specific app configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApps200ResponseAppsInnerAndroid {
    /// Android package name (e.g., \"com.example.myapp\").
    #[serde(rename = "packageName")]
    pub package_name: String,
    /// SHA-1 certificate fingerprints for app verification.
    #[serde(rename = "sha1Hashes", skip_serializing_if = "Option::is_none")]
    pub sha1_hashes: Option<Vec<String>>,
    /// SHA-256 certificate fingerprints for app verification.
    #[serde(rename = "sha256Hashes", skip_serializing_if = "Option::is_none")]
    pub sha256_hashes: Option<Vec<String>>,
}

impl ListApps200ResponseAppsInnerAndroid {
    /// Android-specific app configuration.
    pub fn new(package_name: String) -> ListApps200ResponseAppsInnerAndroid {
        ListApps200ResponseAppsInnerAndroid {
            package_name,
            sha1_hashes: None,
            sha256_hashes: None,
        }
    }
}
