/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjects400Response : RFC 7807 Problem Details error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects400Response {
    /// A URI reference that identifies the problem type
    #[serde(rename = "type")]
    pub r#type: String,
    /// A short, human-readable summary of the problem type
    #[serde(rename = "title")]
    pub title: String,
    /// The HTTP status code
    #[serde(rename = "status")]
    pub status: i32,
    /// A human-readable explanation specific to this occurrence
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// A URI reference that identifies the specific occurrence
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Extension member for validation errors. Contains details about which parameters failed validation and why.
    #[serde(rename = "invalidParams", skip_serializing_if = "Option::is_none")]
    pub invalid_params: Option<Vec<models::ListProjects400ResponseInvalidParamsInner>>,
}

impl ListProjects400Response {
    /// RFC 7807 Problem Details error response
    pub fn new(r#type: String, title: String, status: i32) -> ListProjects400Response {
        ListProjects400Response {
            r#type,
            title,
            status,
            detail: None,
            instance: None,
            invalid_params: None,
        }
    }
}
