/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListApiKeys200ResponseApiKeysInnerRestrictionsBrowserKeyRestrictions : Restrictions for browser API keys.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApiKeys200ResponseApiKeysInnerRestrictionsBrowserKeyRestrictions {
    /// List of allowed HTTP referrer patterns. Supports wildcards: *.example.com
    #[serde(rename = "allowedReferrers", skip_serializing_if = "Option::is_none")]
    pub allowed_referrers: Option<Vec<String>>,
}

impl ListApiKeys200ResponseApiKeysInnerRestrictionsBrowserKeyRestrictions {
    /// Restrictions for browser API keys.
    pub fn new() -> ListApiKeys200ResponseApiKeysInnerRestrictionsBrowserKeyRestrictions {
        ListApiKeys200ResponseApiKeysInnerRestrictionsBrowserKeyRestrictions {
            allowed_referrers: None,
        }
    }
}
