/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjectAuthProviders200ResponseProvidersInnerPdpka : Configuration for passphrase-derived public key authentication (PDPKA). PDPKA allows users to authenticate using cryptographic keypairs derived from passphrases, providing passwordless authentication.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectAuthProviders200ResponseProvidersInnerPdpka {
    /// Whether new users can sign up using PDPKA.
    #[serde(rename = "allowSignup", skip_serializing_if = "Option::is_none")]
    pub allow_signup: Option<bool>,
}

impl ListProjectAuthProviders200ResponseProvidersInnerPdpka {
    /// Configuration for passphrase-derived public key authentication (PDPKA). PDPKA allows users to authenticate using cryptographic keypairs derived from passphrases, providing passwordless authentication.
    pub fn new() -> ListProjectAuthProviders200ResponseProvidersInnerPdpka {
        ListProjectAuthProviders200ResponseProvidersInnerPdpka { allow_signup: None }
    }
}
