/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjects400ResponseInvalidParamsInner : Details about an invalid parameter in a validation error
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects400ResponseInvalidParamsInner {
    /// The name of the invalid parameter
    #[serde(rename = "name")]
    pub name: String,
    /// A human-readable explanation of why the parameter is invalid
    #[serde(rename = "reason")]
    pub reason: String,
    /// The invalid value that was provided
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// The list of valid/expected values for this parameter
    #[serde(rename = "expectedValues", skip_serializing_if = "Option::is_none")]
    pub expected_values: Option<Vec<String>>,
}

impl ListProjects400ResponseInvalidParamsInner {
    /// Details about an invalid parameter in a validation error
    pub fn new(name: String, reason: String) -> ListProjects400ResponseInvalidParamsInner {
        ListProjects400ResponseInvalidParamsInner {
            name,
            reason,
            value: None,
            expected_values: None,
        }
    }
}
