/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListTenants200Response : Response containing a page of tenants.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTenants200Response {
    /// The list of tenants.
    #[serde(rename = "tenants", skip_serializing_if = "Option::is_none")]
    pub tenants: Option<Vec<models::ListTenants200ResponseTenantsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListTenants200ResponsePagination>>,
}

impl ListTenants200Response {
    /// Response containing a page of tenants.
    pub fn new() -> ListTenants200Response {
        ListTenants200Response {
            tenants: None,
            pagination: None,
        }
    }
}
