/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// ListProjects200Response : Response containing a page of projects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects200Response {
    /// The list of projects.
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::ListProjects200ResponseProjectsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListProjects200ResponsePagination>>,
}

impl ListProjects200Response {
    /// Response containing a page of projects.
    pub fn new() -> ListProjects200Response {
        ListProjects200Response {
            projects: None,
            pagination: None,
        }
    }
}
