/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// RotateApiKeyRequest : Request body for rotating an API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateApiKeyRequest {
    /// Grace period in seconds during which the previous key remains valid. Allows for zero-downtime key rotation. Default: 86400 (24 hours). Maximum: 604800 (7 days). Set to 0 to immediately invalidate the previous key.
    #[serde(rename = "gracePeriodSeconds", skip_serializing_if = "Option::is_none")]
    pub grace_period_seconds: Option<i64>,
}

impl RotateApiKeyRequest {
    /// Request body for rotating an API key.
    pub fn new() -> RotateApiKeyRequest {
        RotateApiKeyRequest {
            grace_period_seconds: None,
        }
    }
}
