/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// RotateApiKey200Response : Response containing the rotated API key. IMPORTANT: The new keyString is only returned once and cannot be retrieved again.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateApiKey200Response {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Box<models::CreateApiKey201ResponseApiKey>>,
    /// The previous key string. This key will remain valid for a grace period (typically 24 hours) to allow for key rotation without downtime.
    #[serde(rename = "previousKeyString", skip_serializing_if = "Option::is_none")]
    pub previous_key_string: Option<String>,
}

impl RotateApiKey200Response {
    /// Response containing the rotated API key. IMPORTANT: The new keyString is only returned once and cannot be retrieved again.
    pub fn new() -> RotateApiKey200Response {
        RotateApiKey200Response {
            api_key: None,
            previous_key_string: None,
        }
    }
}
