/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchServiceAccountsRequest : Request body for searching service accounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchServiceAccountsRequest {
    /// Search query string. Searches across service_account_id, display_name, email, and description fields.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Filter expression to narrow results. Supports field-level filtering like \"disabled=true\" or \"created_at>2024-01-01\".
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    /// Number of results to return per page.
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Cursor for pagination. Use \"*\" for first page.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Sort specification. Format: \"field:DIRECTION\" (e.g., \"created_at:DESC\"). Multiple fields separated by commas.
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
}

impl SearchServiceAccountsRequest {
    /// Request body for searching service accounts.
    pub fn new() -> SearchServiceAccountsRequest {
        SearchServiceAccountsRequest {
            query: None,
            filter: None,
            page_size: None,
            cursor: None,
            sort: None,
        }
    }
}
