/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchProjects200Response : Response containing search results for projects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProjects200Response {
    /// The list of projects matching the search query.
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::ListProjects200ResponseProjectsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListTenants200ResponsePagination>>,
}

impl SearchProjects200Response {
    /// Response containing search results for projects.
    pub fn new() -> SearchProjects200Response {
        SearchProjects200Response {
            projects: None,
            pagination: None,
        }
    }
}
