/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchProjectsPostRequestParams : Common search parameters for search endpoints. Extends PaginationParams with a query field for full-text search.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProjectsPostRequestParams {
    /// Query string for searching.  Supports: - Terms: `alice` (searches all fields with OR) - Phrases: `\"Alice Smith\"` (exact phrase match) - Field queries: `username:alice` (specific field) - Wildcards: `ali*` (prefix), `*@example.com` (suffix) - Boolean operators: `AND`, `OR`, `NOT` - Grouping: `(alice OR bob) AND email:*@corp.com` - Ranges: `created_at:[2024-01-01 TO 2024-12-31]` (inclusive) - Boosting: `username:alice^2.0`  Empty string or \"*\" returns all documents (list semantics).
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::SearchProjectsPostRequestParamsPagination>>,
}

impl SearchProjectsPostRequestParams {
    /// Common search parameters for search endpoints. Extends PaginationParams with a query field for full-text search.
    pub fn new() -> SearchProjectsPostRequestParams {
        SearchProjectsPostRequestParams {
            query: None,
            pagination: None,
        }
    }
}
