/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchProjectsRequestParamsPagination : Common pagination parameters for list endpoints. Can be embedded in list request messages or composed into SearchParams.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProjectsRequestParamsPagination {
    /// Number of results to return per page. Defaults to 20, maximum is 100.
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Cursor for pagination. Use \"*\" for the first page of results. Use the `nextCursor` from the previous response for subsequent pages. When cursor is provided (and not \"*\"), the sort parameter is ignored.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Sort specification as an ordered list of fields. Each endpoint defines its own default sort and valid fields. Ignored when cursor is provided (except for \"*\").
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Vec<models::SearchProjectsRequestParamsPaginationSortInner>>,
}

impl SearchProjectsRequestParamsPagination {
    /// Common pagination parameters for list endpoints. Can be embedded in list request messages or composed into SearchParams.
    pub fn new() -> SearchProjectsRequestParamsPagination {
        SearchProjectsRequestParamsPagination {
            page_size: None,
            cursor: None,
            sort: None,
        }
    }
}
