/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchProjectsRequestParamsPaginationSortInner : Specifies a field and direction for sorting.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProjectsRequestParamsPaginationSortInner {
    /// The field name to sort by. Valid fields are endpoint-specific.
    #[serde(rename = "field")]
    pub field: String,
    /// Sort direction for ordering results.
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
}

impl SearchProjectsRequestParamsPaginationSortInner {
    /// Specifies a field and direction for sorting.
    pub fn new(field: String) -> SearchProjectsRequestParamsPaginationSortInner {
        SearchProjectsRequestParamsPaginationSortInner {
            field,
            direction: None,
        }
    }
}
/// Sort direction for ordering results.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "ASC")]
    Asc,
    #[serde(rename = "DESC")]
    Desc,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Asc
    }
}
