/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchProjectsRequest : Request body for searching projects. By default, only ACTIVE projects are returned unless a state filter is specified. Use \"state:DELETED\" to find deleted projects, or \"state:*\" to include all states.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProjectsRequest {
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<models::SearchProjectsRequestParams>>,
}

impl SearchProjectsRequest {
    /// Request body for searching projects. By default, only ACTIVE projects are returned unless a state filter is specified. Use \"state:DELETED\" to find deleted projects, or \"state:*\" to include all states.
    pub fn new() -> SearchProjectsRequest {
        SearchProjectsRequest { params: None }
    }
}
