/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SearchServiceAccounts200Response : Response containing service accounts matching the search query.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchServiceAccounts200Response {
    /// The list of service accounts matching the search.
    #[serde(rename = "serviceAccounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<Vec<models::ListServiceAccounts200ResponseServiceAccountsInner>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::ListTenants200ResponsePagination>>,
}

impl SearchServiceAccounts200Response {
    /// Response containing service accounts matching the search query.
    pub fn new() -> SearchServiceAccounts200Response {
        SearchServiceAccounts200Response {
            service_accounts: None,
            pagination: None,
        }
    }
}
