/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// SetProjectUserCustomClaimsRequest : Request body for setting custom claims on a user. Custom claims are included in the user's ID token and can be used for application-specific authorization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetProjectUserCustomClaimsRequest {
    /// Custom claims to set on the user. Maximum size: 1000 bytes when JSON-encoded. Set to null or {} to clear all custom claims.
    #[serde(rename = "customClaims")]
    pub custom_claims: std::collections::HashMap<String, serde_json::Value>,
}

impl SetProjectUserCustomClaimsRequest {
    /// Request body for setting custom claims on a user. Custom claims are included in the user's ID token and can be used for application-specific authorization.
    pub fn new(
        custom_claims: std::collections::HashMap<String, serde_json::Value>,
    ) -> SetProjectUserCustomClaimsRequest {
        SetProjectUserCustomClaimsRequest { custom_claims }
    }
}
