/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UndeleteProject200Response : Response containing the restored project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UndeleteProject200Response {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::ListProjects200ResponseProjectsInner>>,
}

impl UndeleteProject200Response {
    /// Response containing the restored project.
    pub fn new() -> UndeleteProject200Response {
        UndeleteProject200Response { project: None }
    }
}
