/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateProjectAuthProviderRequest : Request to create or update an auth provider for a project. This is an upsert operation: creates if not exists, updates if exists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectAuthProviderRequest {
    /// Whether this provider is enabled. Defaults to true for new providers.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Display order in sign-in UI. Defaults to 0 for new providers.
    #[serde(rename = "displayOrder", skip_serializing_if = "Option::is_none")]
    pub display_order: Option<i32>,
    #[serde(rename = "pdpka", skip_serializing_if = "Option::is_none")]
    pub pdpka: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerPdpka>>,
    #[serde(rename = "anonymous", skip_serializing_if = "Option::is_none")]
    pub anonymous: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerAnonymous>>,
    #[serde(rename = "oauth", skip_serializing_if = "Option::is_none")]
    pub oauth: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerOauth>>,
    #[serde(rename = "oidc", skip_serializing_if = "Option::is_none")]
    pub oidc: Option<Box<models::ListProjectAuthProviders200ResponseProvidersInnerOidc>>,
    /// Client secret for OAuth/OIDC providers (write-only). For security, secrets are stored as references and never returned in responses.
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
}

impl UpdateProjectAuthProviderRequest {
    /// Request to create or update an auth provider for a project. This is an upsert operation: creates if not exists, updates if exists.
    pub fn new() -> UpdateProjectAuthProviderRequest {
        UpdateProjectAuthProviderRequest {
            enabled: None,
            display_order: None,
            pdpka: None,
            anonymous: None,
            oauth: None,
            oidc: None,
            client_secret: None,
        }
    }
}
