/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateApiKey200Response : Response containing the updated API key metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApiKey200Response {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Box<models::ListApiKeys200ResponseApiKeysInner>>,
}

impl UpdateApiKey200Response {
    /// Response containing the updated API key metadata.
    pub fn new() -> UpdateApiKey200Response {
        UpdateApiKey200Response { api_key: None }
    }
}
