/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateTenantRequest : Request body for updating an existing tenant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTenantRequest {
    /// New display name for the tenant. If not provided (omitted from JSON), the display name will not be changed.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether PDPKA sign-up is allowed. If not provided, the value will not be changed.
    #[serde(rename = "allowPdpkaSignup", skip_serializing_if = "Option::is_none")]
    pub allow_pdpka_signup: Option<bool>,
    /// Whether authentication is disabled. If not provided, the value will not be changed.
    #[serde(rename = "disableAuth", skip_serializing_if = "Option::is_none")]
    pub disable_auth: Option<bool>,
    /// Enabled MFA providers for this tenant. If not provided (omitted) or null, the configuration will not be changed. If provided as an empty array [], clears all MFA providers. If provided with values, replaces the existing configuration. Valid values: \"phone\", \"totp\"
    #[serde(
        rename = "mfaConfig",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mfa_config: Option<Option<Vec<MfaConfig>>>,
}

impl UpdateTenantRequest {
    /// Request body for updating an existing tenant.
    pub fn new() -> UpdateTenantRequest {
        UpdateTenantRequest {
            display_name: None,
            allow_pdpka_signup: None,
            disable_auth: None,
            mfa_config: None,
        }
    }
}
/// Enabled MFA providers for this tenant. If not provided (omitted) or null, the configuration will not be changed. If provided as an empty array [], clears all MFA providers. If provided with values, replaces the existing configuration. Valid values: \"phone\", \"totp\"
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaConfig {
    #[serde(rename = "phone")]
    Phone,
    #[serde(rename = "totp")]
    Totp,
}

impl Default for MfaConfig {
    fn default() -> MfaConfig {
        Self::Phone
    }
}
