/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateAppRequest : Request body for updating an existing app.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAppRequest {
    /// New display name for the app. If not provided (omitted from JSON), the display name will not be changed.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "ios", skip_serializing_if = "Option::is_none")]
    pub ios: Option<Box<models::ListApps200ResponseAppsInnerIos>>,
    #[serde(rename = "android", skip_serializing_if = "Option::is_none")]
    pub android: Option<Box<models::ListApps200ResponseAppsInnerAndroid>>,
    #[serde(rename = "macos", skip_serializing_if = "Option::is_none")]
    pub macos: Option<Box<models::ListApps200ResponseAppsInnerMacos>>,
    #[serde(rename = "windows", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<models::ListApps200ResponseAppsInnerWindows>>,
    #[serde(rename = "linux", skip_serializing_if = "Option::is_none")]
    pub linux: Option<Box<models::ListApps200ResponseAppsInnerLinux>>,
    #[serde(rename = "web", skip_serializing_if = "Option::is_none")]
    pub web: Option<Box<models::ListApps200ResponseAppsInnerWeb>>,
}

impl UpdateAppRequest {
    /// Request body for updating an existing app.
    pub fn new() -> UpdateAppRequest {
        UpdateAppRequest {
            display_name: None,
            ios: None,
            android: None,
            macos: None,
            windows: None,
            linux: None,
            web: None,
        }
    }
}
