/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateProjectQuotasRequest : Request body for updating project quotas. Only provided fields are updated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectQuotasRequest {
    /// Maximum number of users. -1 for unlimited.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<i64>,
    /// Maximum number of service accounts. -1 for unlimited.
    #[serde(rename = "serviceAccounts", skip_serializing_if = "Option::is_none")]
    pub service_accounts: Option<i64>,
    /// Maximum number of tenants. -1 for unlimited.
    #[serde(rename = "tenants", skip_serializing_if = "Option::is_none")]
    pub tenants: Option<i64>,
    /// Maximum number of apps. -1 for unlimited.
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<i64>,
    /// Maximum API keys per app. -1 for unlimited.
    #[serde(rename = "apiKeysPerApp", skip_serializing_if = "Option::is_none")]
    pub api_keys_per_app: Option<i64>,
    /// Maximum requests per minute. -1 for unlimited.
    #[serde(rename = "requestsPerMinute", skip_serializing_if = "Option::is_none")]
    pub requests_per_minute: Option<i64>,
    /// Maximum requests per day. -1 for unlimited.
    #[serde(rename = "requestsPerDay", skip_serializing_if = "Option::is_none")]
    pub requests_per_day: Option<i64>,
    /// Maximum requests per second (burst protection). -1 for unlimited.
    #[serde(rename = "requestsPerSecond", skip_serializing_if = "Option::is_none")]
    pub requests_per_second: Option<i64>,
}

impl UpdateProjectQuotasRequest {
    /// Request body for updating project quotas. Only provided fields are updated.
    pub fn new() -> UpdateProjectQuotasRequest {
        UpdateProjectQuotasRequest {
            users: None,
            service_accounts: None,
            tenants: None,
            apps: None,
            api_keys_per_app: None,
            requests_per_minute: None,
            requests_per_day: None,
            requests_per_second: None,
        }
    }
}
