/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateTenantAuthProvider200Response : Response containing the created or updated override.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTenantAuthProvider200Response {
    #[serde(rename = "override", skip_serializing_if = "Option::is_none")]
    pub r#override: Option<Box<models::ListTenantAuthProviders200ResponseOverridesInner>>,
}

impl UpdateTenantAuthProvider200Response {
    /// Response containing the created or updated override.
    pub fn new() -> UpdateTenantAuthProvider200Response {
        UpdateTenantAuthProvider200Response { r#override: None }
    }
}
