/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateServiceAccount200Response : Response containing the updated service account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateServiceAccount200Response {
    #[serde(rename = "serviceAccount", skip_serializing_if = "Option::is_none")]
    pub service_account: Option<Box<models::ListServiceAccounts200ResponseServiceAccountsInner>>,
}

impl UpdateServiceAccount200Response {
    /// Response containing the updated service account.
    pub fn new() -> UpdateServiceAccount200Response {
        UpdateServiceAccount200Response {
            service_account: None,
        }
    }
}
