/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// UpdateProjectUserRequest : Request body for updating an existing user. Only provided fields are updated; omitted fields retain their current values. To clear a nullable field, explicitly set it to null.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectUserRequest {
    /// New email address for the user. If not provided, the email will not be changed. Set to null to clear the email.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the email has been verified. If not provided, the value will not be changed.
    #[serde(rename = "emailVerified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    /// New phone number in E.164 format. If not provided, the phone number will not be changed. Set to null to clear the phone number.
    #[serde(
        rename = "phoneNumber",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// New display name for the user. If not provided, the display name will not be changed. Set to null to clear the display name.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// New photo URL for the user. If not provided, the photo URL will not be changed. Set to null to clear the photo URL.
    #[serde(
        rename = "photoUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub photo_url: Option<Option<String>>,
    /// Whether the account is disabled. If not provided, the value will not be changed.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Custom claims for the ID token. If not provided, the claims will not be changed. Set to null or {} to clear all custom claims.
    #[serde(rename = "customClaims", skip_serializing_if = "Option::is_none")]
    pub custom_claims: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl UpdateProjectUserRequest {
    /// Request body for updating an existing user. Only provided fields are updated; omitted fields retain their current values. To clear a nullable field, explicitly set it to null.
    pub fn new() -> UpdateProjectUserRequest {
        UpdateProjectUserRequest {
            email: None,
            email_verified: None,
            phone_number: None,
            display_name: None,
            photo_url: None,
            disabled: None,
            custom_claims: None,
        }
    }
}
