/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// VerifySessionCookieRequest : Request body for verifying a session cookie.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifySessionCookieRequest {
    /// The session cookie to verify.
    #[serde(rename = "sessionCookie")]
    pub session_cookie: String,
    /// Whether to check if the session has been revoked. This adds a backend check and increases latency.
    #[serde(rename = "checkRevoked", skip_serializing_if = "Option::is_none")]
    pub check_revoked: Option<bool>,
}

impl VerifySessionCookieRequest {
    /// Request body for verifying a session cookie.
    pub fn new(session_cookie: String) -> VerifySessionCookieRequest {
        VerifySessionCookieRequest {
            session_cookie,
            check_revoked: None,
        }
    }
}
