/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// VerifyIdToken200Response : Response containing the decoded and verified token claims.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyIdToken200Response {
    /// Whether the token is valid.
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<bool>,
    /// The user's pistachio_id.
    #[serde(rename = "pistachioId", skip_serializing_if = "Option::is_none")]
    pub pistachio_id: Option<String>,
    /// The user's email address.
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    /// Whether the user's email has been verified.
    #[serde(rename = "emailVerified", skip_serializing_if = "Option::is_none")]
    pub email_verified: Option<bool>,
    /// All claims from the token.
    #[serde(rename = "claims", skip_serializing_if = "Option::is_none")]
    pub claims: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl VerifyIdToken200Response {
    /// Response containing the decoded and verified token claims.
    pub fn new() -> VerifyIdToken200Response {
        VerifyIdToken200Response {
            valid: None,
            pistachio_id: None,
            email: None,
            email_verified: None,
            claims: None,
        }
    }
}
