/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::generated_admin::models;
use serde::{Deserialize, Serialize};

/// VerifyIdTokenRequest : Request body for verifying an ID token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyIdTokenRequest {
    /// The ID token to verify.
    #[serde(rename = "idToken")]
    pub id_token: String,
    /// Whether to check if the token has been revoked. This adds a backend check and increases latency.
    #[serde(rename = "checkRevoked", skip_serializing_if = "Option::is_none")]
    pub check_revoked: Option<bool>,
}

impl VerifyIdTokenRequest {
    /// Request body for verifying an ID token.
    pub fn new(id_token: String) -> VerifyIdTokenRequest {
        VerifyIdTokenRequest {
            id_token,
            check_revoked: None,
        }
    }
}
