/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::generated_admin::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`create_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateApiKeyError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteApiKeyError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiKeyError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_api_keys`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListApiKeysError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rotate_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateApiKeyError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// Creates a new API key for an app. IMPORTANT: The full key string is only returned in this response. Store it securely as it cannot be retrieved again.
pub async fn create_api_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    app_id: &str,
    create_api_key_request: Option<models::CreateApiKeyRequest>,
) -> Result<models::CreateApiKey201Response, Error<CreateApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_app_id = app_id;
    let p_body_create_api_key_request = create_api_key_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/apps/{appId}/apiKeys",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        appId = crate::generated_admin::apis::urlencode(p_path_app_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_api_key_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::CreateApiKey201Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::CreateApiKey201Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Permanently deletes an API key. This operation is irreversible. Any requests using this key will fail.
pub async fn delete_api_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    app_id: &str,
    key_id: &str,
) -> Result<(), Error<DeleteApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_app_id = app_id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/apps/{appId}/apiKeys/{keyId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        appId = crate::generated_admin::apis::urlencode(p_path_app_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves an API key by ID. For security, only a masked key prefix is returned. The full key string is only available when creating or rotating a key.
pub async fn get_api_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    app_id: &str,
    key_id: &str,
) -> Result<models::GetApiKey200Response, Error<GetApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_app_id = app_id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/apps/{appId}/apiKeys/{keyId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        appId = crate::generated_admin::apis::urlencode(p_path_app_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetApiKey200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetApiKey200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all API keys for an app within a project. Results are paginated with cursor-based pagination.
pub async fn list_api_keys(
    configuration: &configuration::Configuration,
    project_id: &str,
    app_id: &str,
    page_size: Option<i32>,
    cursor: Option<&str>,
    sort: Option<&str>,
) -> Result<models::ListApiKeys200Response, Error<ListApiKeysError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_app_id = app_id;
    let p_query_page_size = page_size;
    let p_query_cursor = cursor;
    let p_query_sort = sort;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/apps/{appId}/apiKeys",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        appId = crate::generated_admin::apis::urlencode(p_path_app_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListApiKeys200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListApiKeys200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListApiKeysError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Rotates an API key, generating a new key string. The previous key remains valid for a configurable grace period (default 24 hours) to allow for key rotation without downtime.
pub async fn rotate_api_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    app_id: &str,
    key_id: &str,
    rotate_api_key_request: Option<models::RotateApiKeyRequest>,
) -> Result<models::RotateApiKey200Response, Error<RotateApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_app_id = app_id;
    let p_path_key_id = key_id;
    let p_body_rotate_api_key_request = rotate_api_key_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/apps/{appId}/apiKeys/{keyId}:rotate",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        appId = crate::generated_admin::apis::urlencode(p_path_app_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_rotate_api_key_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::RotateApiKey200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::RotateApiKey200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RotateApiKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
