/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::generated_admin::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`delete_project_auth_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProjectAuthProviderError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_tenant_auth_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTenantAuthProviderError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_effective_tenant_auth_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEffectiveTenantAuthProvidersError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_project_auth_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProjectAuthProviderError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_project_auth_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListProjectAuthProvidersError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_tenant_auth_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTenantAuthProvidersError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_project_auth_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateProjectAuthProviderError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_tenant_auth_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTenantAuthProviderError {
    Status400(models::ListProjects400Response),
    Status401(models::ListProjects400Response),
    Status403(models::ListProjects400Response),
    Status404(models::ListProjects400Response),
    Status500(models::ListProjects400Response),
    Status503(models::ListProjects400Response),
    UnknownValue(serde_json::Value),
}

/// Permanently deletes an authentication provider from a project. This operation is irreversible.
pub async fn delete_project_auth_provider(
    configuration: &configuration::Configuration,
    project_id: &str,
    provider_id: &str,
) -> Result<(), Error<DeleteProjectAuthProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_provider_id = provider_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/authProviders/{providerId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        providerId = crate::generated_admin::apis::urlencode(p_path_provider_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteProjectAuthProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Removes a tenant-level authentication provider override. After deletion, the tenant will inherit the project-level configuration.
pub async fn delete_tenant_auth_provider(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
    provider_id: &str,
) -> Result<(), Error<DeleteTenantAuthProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;
    let p_path_provider_id = provider_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}/authProviders/{providerId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id),
        providerId = crate::generated_admin::apis::urlencode(p_path_provider_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTenantAuthProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves the effective authentication provider configuration for a tenant. Returns the merged configuration after applying tenant-level overrides to project-level configuration. Each provider includes its source (PROJECT or TENANT).
pub async fn get_effective_tenant_auth_providers(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
    enabled_only: Option<bool>,
) -> Result<
    models::GetEffectiveTenantAuthProviders200Response,
    Error<GetEffectiveTenantAuthProvidersError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;
    let p_query_enabled_only = enabled_only;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}/authProviders:effective",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_enabled_only {
        req_builder = req_builder.query(&[("enabledOnly", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetEffectiveTenantAuthProviders200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetEffectiveTenantAuthProviders200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEffectiveTenantAuthProvidersError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a specific authentication provider configuration for a project.
pub async fn get_project_auth_provider(
    configuration: &configuration::Configuration,
    project_id: &str,
    provider_id: &str,
) -> Result<models::GetProjectAuthProvider200Response, Error<GetProjectAuthProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_provider_id = provider_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/authProviders/{providerId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        providerId = crate::generated_admin::apis::urlencode(p_path_provider_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetProjectAuthProvider200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetProjectAuthProvider200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetProjectAuthProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all authentication providers configured for a project. Providers are returned ordered by displayOrder.
pub async fn list_project_auth_providers(
    configuration: &configuration::Configuration,
    project_id: &str,
) -> Result<models::ListProjectAuthProviders200Response, Error<ListProjectAuthProvidersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/authProviders",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListProjectAuthProviders200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListProjectAuthProviders200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListProjectAuthProvidersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all tenant-level authentication provider overrides. Returns only the overrides explicitly set for this tenant.
pub async fn list_tenant_auth_providers(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
) -> Result<models::ListTenantAuthProviders200Response, Error<ListTenantAuthProvidersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}/authProviders",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListTenantAuthProviders200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListTenantAuthProviders200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTenantAuthProvidersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates or updates an authentication provider for a project. This is an upsert operation: creates the provider if it doesn't exist, updates it if it does.
pub async fn update_project_auth_provider(
    configuration: &configuration::Configuration,
    project_id: &str,
    provider_id: &str,
    update_project_auth_provider_request: models::UpdateProjectAuthProviderRequest,
) -> Result<models::UpdateProjectAuthProvider200Response, Error<UpdateProjectAuthProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_provider_id = provider_id;
    let p_body_update_project_auth_provider_request = update_project_auth_provider_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/authProviders/{providerId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        providerId = crate::generated_admin::apis::urlencode(p_path_provider_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_project_auth_provider_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::UpdateProjectAuthProvider200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::UpdateProjectAuthProvider200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateProjectAuthProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates or updates a tenant-level authentication provider override. Fields that are null or omitted will inherit from the project configuration.
pub async fn update_tenant_auth_provider(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
    provider_id: &str,
    update_tenant_auth_provider_request: models::UpdateTenantAuthProviderRequest,
) -> Result<models::UpdateTenantAuthProvider200Response, Error<UpdateTenantAuthProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;
    let p_path_provider_id = provider_id;
    let p_body_update_tenant_auth_provider_request = update_tenant_auth_provider_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}/authProviders/{providerId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id),
        providerId = crate::generated_admin::apis::urlencode(p_path_provider_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_tenant_auth_provider_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::UpdateTenantAuthProvider200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTenantAuthProvider200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTenantAuthProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
