/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::generated_admin::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`create_service_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateServiceAccountError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status409(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_service_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteServiceAccountError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_service_account_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteServiceAccountKeyError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_service_account_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableServiceAccountKeyError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enable_service_account_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnableServiceAccountKeyError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`generate_service_account_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GenerateServiceAccountKeyError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_service_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetServiceAccountError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_service_account_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetServiceAccountKeyError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_service_account_keys`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListServiceAccountKeysError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_service_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListServiceAccountsError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_service_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchServiceAccountsError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_service_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateServiceAccountError {
    Status400(models::ListTenants400Response),
    Status401(models::ListTenants400Response),
    Status403(models::ListTenants400Response),
    Status404(models::ListTenants400Response),
    Status500(models::ListTenants400Response),
    Status503(models::ListTenants400Response),
    UnknownValue(serde_json::Value),
}

/// Creates a new service account within a project. The service account ID is system-generated if not provided.
pub async fn create_service_account(
    configuration: &configuration::Configuration,
    project_id: &str,
    create_service_account_request: models::CreateServiceAccountRequest,
) -> Result<models::CreateServiceAccount201Response, Error<CreateServiceAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_body_create_service_account_request = create_service_account_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_service_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::CreateServiceAccount201Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::CreateServiceAccount201Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateServiceAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Permanently deletes a service account. This operation is irreversible. All keys associated with the service account will also be deleted.
pub async fn delete_service_account(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
) -> Result<(), Error<DeleteServiceAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteServiceAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Permanently deletes a service account key. This operation is irreversible.
pub async fn delete_service_account_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    key_id: &str,
) -> Result<(), Error<DeleteServiceAccountKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys/{keyId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteServiceAccountKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Disables a service account key without deleting it. Disabled keys cannot be used for authentication.  This operation is idempotent. Calling disable on an already-disabled key returns 200 OK with the current key state.
pub async fn disable_service_account_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    key_id: &str,
) -> Result<models::DisableServiceAccountKey200Response, Error<DisableServiceAccountKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys/{keyId}:disable",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::DisableServiceAccountKey200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::DisableServiceAccountKey200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DisableServiceAccountKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Re-enables a previously disabled service account key.
pub async fn enable_service_account_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    key_id: &str,
) -> Result<models::EnableServiceAccountKey200Response, Error<EnableServiceAccountKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys/{keyId}:enable",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::EnableServiceAccountKey200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::EnableServiceAccountKey200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EnableServiceAccountKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Generates a new key for a service account. The private key data is only returned once in the response and cannot be retrieved again. Store the key securely.
pub async fn generate_service_account_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    generate_service_account_key_request: Option<models::GenerateServiceAccountKeyRequest>,
) -> Result<models::GenerateServiceAccountKey201Response, Error<GenerateServiceAccountKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_body_generate_service_account_key_request = generate_service_account_key_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_generate_service_account_key_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GenerateServiceAccountKey201Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GenerateServiceAccountKey201Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GenerateServiceAccountKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a service account by ID. Returns the service account's metadata including display name and status.
pub async fn get_service_account(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
) -> Result<models::GetServiceAccount200Response, Error<GetServiceAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetServiceAccount200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetServiceAccount200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetServiceAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a specific key by ID. Note: Private key data is never returned after initial generation.
pub async fn get_service_account_key(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    key_id: &str,
) -> Result<models::GetServiceAccountKey200Response, Error<GetServiceAccountKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_path_key_id = key_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys/{keyId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id),
        keyId = crate::generated_admin::apis::urlencode(p_path_key_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetServiceAccountKey200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetServiceAccountKey200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetServiceAccountKeyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all keys for a service account. Note: Private key data is never returned after initial generation.
pub async fn list_service_account_keys(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
) -> Result<models::ListServiceAccountKeys200Response, Error<ListServiceAccountKeysError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}/keys",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListServiceAccountKeys200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListServiceAccountKeys200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListServiceAccountKeysError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all service accounts within a project. Results are paginated with cursor-based pagination.
pub async fn list_service_accounts(
    configuration: &configuration::Configuration,
    project_id: &str,
    page_size: Option<i32>,
    cursor: Option<&str>,
    sort: Option<&str>,
) -> Result<models::ListServiceAccounts200Response, Error<ListServiceAccountsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_query_page_size = page_size;
    let p_query_cursor = cursor;
    let p_query_sort = sort;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListServiceAccounts200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListServiceAccounts200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListServiceAccountsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Searches for service accounts within a project. Supports full-text search across multiple fields and filtering.
pub async fn search_service_accounts(
    configuration: &configuration::Configuration,
    project_id: &str,
    search_service_accounts_request: models::SearchServiceAccountsRequest,
) -> Result<models::SearchServiceAccounts200Response, Error<SearchServiceAccountsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_body_search_service_accounts_request = search_service_accounts_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts:search",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_search_service_accounts_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::SearchServiceAccounts200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::SearchServiceAccounts200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchServiceAccountsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing service account. Only provided fields are updated; omitted fields retain their current values.
pub async fn update_service_account(
    configuration: &configuration::Configuration,
    project_id: &str,
    id: &str,
    update_service_account_request: models::UpdateServiceAccountRequest,
) -> Result<models::UpdateServiceAccount200Response, Error<UpdateServiceAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_id = id;
    let p_body_update_service_account_request = update_service_account_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/serviceAccounts/{id}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        id = crate::generated_admin::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_service_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::UpdateServiceAccount200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::UpdateServiceAccount200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateServiceAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
