/*
 * Pistachio Admin API
 *
 * Administrative API for managing Pistachio projects and resources. Requires service account authentication.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::generated_admin::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`create_tenant`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTenantError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status409(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_tenant`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTenantError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_tenant`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTenantError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_tenants`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTenantsError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_tenants`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchTenantsError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_tenants_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchTenantsPostError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_tenant`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTenantError {
    Status400(models::ListApps400Response),
    Status401(models::ListApps400Response),
    Status403(models::ListApps400Response),
    Status404(models::ListApps400Response),
    Status500(models::ListApps400Response),
    Status503(models::ListApps400Response),
    UnknownValue(serde_json::Value),
}

/// Creates a new tenant within a project. Tenants provide multi-tenant isolation, allowing each tenant to have its own user pool and authentication configuration.
pub async fn create_tenant(
    configuration: &configuration::Configuration,
    project_id: &str,
    create_tenant_request: models::CreateTenantRequest,
) -> Result<models::CreateTenant201Response, Error<CreateTenantError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_body_create_tenant_request = create_tenant_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_tenant_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::CreateTenant201Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::CreateTenant201Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTenantError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Permanently deletes a tenant. This operation is irreversible. All users and data associated with the tenant will be permanently deleted.
pub async fn delete_tenant(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
) -> Result<(), Error<DeleteTenantError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTenantError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a tenant by its ID. Returns the tenant details including its authentication configuration.
pub async fn get_tenant(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
) -> Result<models::GetTenant200Response, Error<GetTenantError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GetTenant200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GetTenant200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTenantError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists all tenants within a project. Results are paginated with cursor-based pagination.
pub async fn list_tenants(
    configuration: &configuration::Configuration,
    project_id: &str,
    page_size: Option<i32>,
    cursor: Option<&str>,
    sort: Option<&str>,
) -> Result<models::ListTenants200Response, Error<ListTenantsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_query_page_size = page_size;
    let p_query_cursor = cursor;
    let p_query_sort = sort;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListTenants200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListTenants200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTenantsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Searches for tenants within a project using full-text search.  Searchable fields: - tenant_id: The unique tenant identifier - display_name: Human-readable display name - allow_pdpka_signup: Whether PDPKA sign-up is allowed - disable_auth: Whether authentication is disabled - created_at: Timestamp when created - updated_at: Timestamp when last updated  Example queries: - \"my_tenant\" - Search all fields - \"display_name:Production*\" - Tenants with display name starting with \"Production\" - \"allow_pdpka_signup:true\" - Tenants with PDPKA sign-up enabled  For complex queries that exceed URL length limits, use POST instead.
pub async fn search_tenants(
    configuration: &configuration::Configuration,
    project_id: &str,
    query: Option<&str>,
    page_size: Option<i32>,
    cursor: Option<&str>,
    sort: Option<&str>,
) -> Result<models::SearchTenants200Response, Error<SearchTenantsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_query_query = query;
    let p_query_page_size = page_size;
    let p_query_cursor = cursor;
    let p_query_sort = sort;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants:search",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::SearchTenants200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::SearchTenants200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchTenantsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Searches for tenants within a project using full-text search. Use this method for complex queries that exceed URL length limits.  Searchable fields: - tenant_id: The unique tenant identifier - display_name: Human-readable display name - allow_pdpka_signup: Whether PDPKA sign-up is allowed - disable_auth: Whether authentication is disabled - created_at: Timestamp when created - updated_at: Timestamp when last updated  Example queries: - \"my_tenant\" - Search all fields - \"display_name:Production*\" - Tenants with display name starting with \"Production\" - \"allow_pdpka_signup:true\" - Tenants with PDPKA sign-up enabled
pub async fn search_tenants_post(
    configuration: &configuration::Configuration,
    project_id: &str,
    search_tenants_post_request: models::SearchTenantsPostRequest,
) -> Result<models::SearchTenants200Response, Error<SearchTenantsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_body_search_tenants_post_request = search_tenants_post_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants:search",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_search_tenants_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::SearchTenants200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::SearchTenants200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchTenantsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing tenant. Updates the tenant's display name, authentication settings, or MFA configuration.
pub async fn update_tenant(
    configuration: &configuration::Configuration,
    project_id: &str,
    tenant_id: &str,
    update_tenant_request: models::UpdateTenantRequest,
) -> Result<models::UpdateTenant200Response, Error<UpdateTenantError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_project_id = project_id;
    let p_path_tenant_id = tenant_id;
    let p_body_update_tenant_request = update_tenant_request;

    let uri_str = format!(
        "{}/admin/v1/projects/{projectId}/tenants/{tenantId}",
        configuration.base_path,
        projectId = crate::generated_admin::apis::urlencode(p_path_project_id),
        tenantId = crate::generated_admin::apis::urlencode(p_path_tenant_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("key", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_tenant_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::UpdateTenant200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTenant200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTenantError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
