//! Service account management types for the Admin API.

use chrono::{DateTime, Utc};
use libgn::project::ProjectId;

use crate::error::{ErrorDetails, PistachioApiClientError, ValidationError};
use crate::pagination::{PaginationMeta, PaginationParams};
use crate::search::SearchParams;

// =============================================================================
// Service Account Domain Types
// =============================================================================

/// A service account for server-to-server authentication.
///
/// Service accounts use key-based authentication and are used for administrative
/// operations and backend integrations. Unlike users, service accounts don't have
/// passwords and authenticate using cryptographic keys.
#[derive(Debug, Clone)]
pub struct ServiceAccount {
    /// Resource name in the format:
    /// "projects/{project_id}/serviceAccounts/{service_account_id}"
    pub name: String,
    /// Unique service account identifier within the project.
    /// 4-128 characters, lowercase alphanumeric with hyphens.
    pub service_account_id: String,
    /// Internal service account identifier.
    /// 16 bytes encoded as 32 hex characters ending in '03'.
    pub pistachio_id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Optional description of the service account's purpose.
    pub description: Option<String>,
    /// Auto-generated email address for the service account.
    pub email: String,
    /// Whether the service account is disabled.
    pub disabled: bool,
    /// Timestamp when the service account was created.
    pub created_at: Option<DateTime<Utc>>,
    /// Timestamp when the service account was last updated.
    pub updated_at: Option<DateTime<Utc>>,
}

/// A key for service account authentication.
#[derive(Debug, Clone)]
pub struct ServiceAccountKey {
    /// Resource name in the format:
    /// "projects/{project_id}/serviceAccounts/{service_account_id}/keys/{key_id}"
    pub name: String,
    /// Unique key identifier.
    pub key_id: String,
    /// The algorithm used for the key pair.
    pub key_algorithm: KeyAlgorithm,
    /// How the key was created.
    pub key_origin: KeyOrigin,
    /// The key becomes valid at this time.
    pub valid_after_time: Option<DateTime<Utc>>,
    /// The key expires at this time.
    pub valid_before_time: Option<DateTime<Utc>>,
    /// Whether the key is disabled.
    pub disabled: bool,
}

/// The cryptographic algorithm used for service account keys.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum KeyAlgorithm {
    /// Unspecified algorithm.
    #[default]
    Unspecified,
    /// RSA 2048-bit key.
    Rsa2048,
    /// RSA 4096-bit key.
    Rsa4096,
    /// Elliptic Curve P-256 key.
    EcP256,
    /// Elliptic Curve P-384 key.
    EcP384,
    /// Ed25519 key (EdDSA).
    Ed25519,
}

/// How a service account key was created.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum KeyOrigin {
    /// Unspecified origin.
    #[default]
    Unspecified,
    /// The key was generated by the Pistachio system.
    SystemProvided,
    /// The key was provided by the user.
    UserProvided,
}

// =============================================================================
// CreateServiceAccount
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum CreateServiceAccountError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account already exists")]
    AlreadyExists,
    #[error("Project not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to create a new service account within a project.
#[derive(Debug, Clone)]
pub struct CreateServiceAccountRequest {
    /// The project ID that will own this service account.
    pub project_id: ProjectId,
    /// Desired service account ID. Optional.
    pub service_account_id: Option<String>,
    /// Human-readable display name.
    pub display_name: String,
    /// Optional description of the service account's purpose.
    pub description: Option<String>,
}

impl CreateServiceAccountRequest {
    /// Creates a new request with required fields only.
    pub fn new(project_id: ProjectId, display_name: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: None,
            display_name: display_name.into(),
            description: None,
        }
    }

    /// Sets the service account ID.
    pub fn with_service_account_id(mut self, id: impl Into<String>) -> Self {
        self.service_account_id = Some(id.into());
        self
    }

    /// Sets the description.
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }
}

/// Response from creating a service account.
#[derive(Debug, Clone)]
pub struct CreateServiceAccountResponse {
    /// The created service account.
    pub service_account: ServiceAccount,
}

// =============================================================================
// GetServiceAccount
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum GetServiceAccountError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to get a service account by ID.
#[derive(Debug, Clone)]
pub struct GetServiceAccountRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
}

impl GetServiceAccountRequest {
    /// Creates a new request for the given project and service account IDs.
    pub fn new(project_id: ProjectId, service_account_id: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
        }
    }
}

/// Response from getting a service account.
#[derive(Debug, Clone)]
pub struct GetServiceAccountResponse {
    /// The retrieved service account.
    pub service_account: ServiceAccount,
}

// =============================================================================
// UpdateServiceAccount
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum UpdateServiceAccountError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to update an existing service account.
#[derive(Debug, Clone)]
pub struct UpdateServiceAccountRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// New display name.
    pub display_name: Option<String>,
    /// New description.
    pub description: Option<String>,
    /// Whether to disable the service account.
    pub disabled: Option<bool>,
}

impl UpdateServiceAccountRequest {
    /// Creates a new request for the given project and service account IDs.
    pub fn new(project_id: ProjectId, service_account_id: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            display_name: None,
            description: None,
            disabled: None,
        }
    }

    /// Sets the display name to update.
    pub fn with_display_name(mut self, name: impl Into<String>) -> Self {
        self.display_name = Some(name.into());
        self
    }

    /// Sets the description.
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Sets the disabled status.
    pub fn with_disabled(mut self, disabled: bool) -> Self {
        self.disabled = Some(disabled);
        self
    }
}

/// Response from updating a service account.
#[derive(Debug, Clone)]
pub struct UpdateServiceAccountResponse {
    /// The updated service account.
    pub service_account: ServiceAccount,
}

// =============================================================================
// DeleteServiceAccount
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum DeleteServiceAccountError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to delete a service account.
#[derive(Debug, Clone)]
pub struct DeleteServiceAccountRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
}

impl DeleteServiceAccountRequest {
    /// Creates a new request for the given project and service account IDs.
    pub fn new(project_id: ProjectId, service_account_id: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
        }
    }
}

/// Response from deleting a service account.
#[derive(Debug, Clone)]
pub struct DeleteServiceAccountResponse {
    // Empty response - the service account has been permanently deleted.
}

// =============================================================================
// ListServiceAccounts
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum ListServiceAccountsError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Project not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to list service accounts within a project.
#[derive(Debug, Clone)]
pub struct ListServiceAccountsRequest {
    /// The project ID to list service accounts from.
    pub project_id: ProjectId,
    /// Pagination parameters.
    pub pagination: PaginationParams,
}

impl ListServiceAccountsRequest {
    /// Creates a new request for the given project ID.
    pub fn new(project_id: ProjectId) -> Self {
        Self {
            project_id,
            pagination: PaginationParams::default(),
        }
    }

    /// Sets the pagination parameters.
    pub fn with_pagination(mut self, pagination: PaginationParams) -> Self {
        self.pagination = pagination;
        self
    }
}

/// Response from listing service accounts.
#[derive(Debug, Clone)]
pub struct ListServiceAccountsResponse {
    /// The list of service accounts.
    pub service_accounts: Vec<ServiceAccount>,
    /// Pagination metadata.
    pub pagination: PaginationMeta,
}

// =============================================================================
// SearchServiceAccounts
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum SearchServiceAccountsError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Project not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to search for service accounts within a project.
#[derive(Debug, Clone)]
pub struct SearchServiceAccountsRequest {
    /// The project ID to search service accounts in.
    pub project_id: ProjectId,
    /// Search parameters including query, sorting, and pagination.
    pub params: SearchParams,
}

impl SearchServiceAccountsRequest {
    /// Creates a new request for the given project ID.
    pub fn new(project_id: ProjectId) -> Self {
        Self {
            project_id,
            params: SearchParams::default(),
        }
    }

    /// Sets the search parameters.
    pub fn with_params(mut self, params: SearchParams) -> Self {
        self.params = params;
        self
    }

    /// Sets the search query.
    pub fn with_query(mut self, query: impl Into<String>) -> Self {
        self.params.query = query.into();
        self
    }
}

/// Response from searching service accounts.
#[derive(Debug, Clone)]
pub struct SearchServiceAccountsResponse {
    /// The list of service accounts matching the search query.
    pub service_accounts: Vec<ServiceAccount>,
    /// Pagination metadata.
    pub pagination: PaginationMeta,
}

// =============================================================================
// GenerateServiceAccountKey
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum GenerateServiceAccountKeyError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to generate a new key for a service account.
#[derive(Debug, Clone)]
pub struct GenerateServiceAccountKeyRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// The algorithm for the key pair.
    pub key_algorithm: KeyAlgorithm,
    /// Optional expiration time for the key.
    pub valid_before_time: Option<DateTime<Utc>>,
}

impl GenerateServiceAccountKeyRequest {
    /// Creates a new request for the given project and service account IDs.
    pub fn new(project_id: ProjectId, service_account_id: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            key_algorithm: KeyAlgorithm::default(),
            valid_before_time: None,
        }
    }

    /// Sets the key algorithm.
    pub fn with_key_algorithm(mut self, algorithm: KeyAlgorithm) -> Self {
        self.key_algorithm = algorithm;
        self
    }

    /// Sets the key expiration time.
    pub fn with_valid_before_time(mut self, time: DateTime<Utc>) -> Self {
        self.valid_before_time = Some(time);
        self
    }
}

/// Response from generating a service account key.
///
/// IMPORTANT: The private_key_data is only returned once and cannot be retrieved again.
#[derive(Debug, Clone)]
pub struct GenerateServiceAccountKeyResponse {
    /// The generated key metadata.
    pub key: ServiceAccountKey,
    /// Base64-encoded private key data in PKCS#8 format.
    /// IMPORTANT: This is only returned once at key creation time.
    pub private_key_data: Vec<u8>,
    /// Key file for SDK authentication.
    /// This is a structured object that can be serialized to JSON and saved for SDK use.
    pub key_file: serde_json::Value,
}

// =============================================================================
// ListServiceAccountKeys
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum ListServiceAccountKeysError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Service account not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to list keys for a service account.
#[derive(Debug, Clone)]
pub struct ListServiceAccountKeysRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
}

impl ListServiceAccountKeysRequest {
    /// Creates a new request for the given project and service account IDs.
    pub fn new(project_id: ProjectId, service_account_id: impl Into<String>) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
        }
    }
}

/// Response from listing service account keys.
#[derive(Debug, Clone)]
pub struct ListServiceAccountKeysResponse {
    /// The list of keys.
    pub keys: Vec<ServiceAccountKey>,
}

// =============================================================================
// GetServiceAccountKey
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum GetServiceAccountKeyError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Key not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to get a specific service account key.
#[derive(Debug, Clone)]
pub struct GetServiceAccountKeyRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// The key ID.
    pub key_id: String,
}

impl GetServiceAccountKeyRequest {
    /// Creates a new request.
    pub fn new(
        project_id: ProjectId,
        service_account_id: impl Into<String>,
        key_id: impl Into<String>,
    ) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            key_id: key_id.into(),
        }
    }
}

/// Response from getting a service account key.
#[derive(Debug, Clone)]
pub struct GetServiceAccountKeyResponse {
    /// The retrieved key metadata.
    pub key: ServiceAccountKey,
}

// =============================================================================
// DeleteServiceAccountKey
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum DeleteServiceAccountKeyError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Key not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to delete a service account key.
#[derive(Debug, Clone)]
pub struct DeleteServiceAccountKeyRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// The key ID.
    pub key_id: String,
}

impl DeleteServiceAccountKeyRequest {
    /// Creates a new request.
    pub fn new(
        project_id: ProjectId,
        service_account_id: impl Into<String>,
        key_id: impl Into<String>,
    ) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            key_id: key_id.into(),
        }
    }
}

/// Response from deleting a service account key.
#[derive(Debug, Clone)]
pub struct DeleteServiceAccountKeyResponse {
    // Empty response - the key has been permanently deleted.
}

// =============================================================================
// DisableServiceAccountKey
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum DisableServiceAccountKeyError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Key not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to disable a service account key.
#[derive(Debug, Clone)]
pub struct DisableServiceAccountKeyRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// The key ID.
    pub key_id: String,
}

impl DisableServiceAccountKeyRequest {
    /// Creates a new request.
    pub fn new(
        project_id: ProjectId,
        service_account_id: impl Into<String>,
        key_id: impl Into<String>,
    ) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            key_id: key_id.into(),
        }
    }
}

/// Response from disabling a service account key.
#[derive(Debug, Clone)]
pub struct DisableServiceAccountKeyResponse {
    /// The disabled key.
    pub key: ServiceAccountKey,
}

// =============================================================================
// EnableServiceAccountKey
// =============================================================================

#[derive(Debug, thiserror::Error)]
pub enum EnableServiceAccountKeyError {
    #[error("Bad request: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    BadRequest(ErrorDetails),
    #[error("Key not found: {}", .0.message.as_deref().unwrap_or(&.0.title))]
    NotFound(ErrorDetails),
    #[error("Unauthenticated: {0}")]
    Unauthenticated(String),
    #[error("Permission denied: {0}")]
    PermissionDenied(String),
    #[error("Service error: {0}")]
    ServiceError(String),
    #[error("Service unavailable: {0}")]
    ServiceUnavailable(String),
    #[error("Client error: {0}")]
    PistachioApiClientError(#[from] PistachioApiClientError),
    #[error("Response validation error: {0}")]
    ResponseValidationError(#[from] ValidationError),
    #[error("Unexpected error: {0}")]
    Unknown(String),
}

/// Request to enable a service account key.
#[derive(Debug, Clone)]
pub struct EnableServiceAccountKeyRequest {
    /// The project ID that owns the service account.
    pub project_id: ProjectId,
    /// The service account ID.
    pub service_account_id: String,
    /// The key ID.
    pub key_id: String,
}

impl EnableServiceAccountKeyRequest {
    /// Creates a new request.
    pub fn new(
        project_id: ProjectId,
        service_account_id: impl Into<String>,
        key_id: impl Into<String>,
    ) -> Self {
        Self {
            project_id,
            service_account_id: service_account_id.into(),
            key_id: key_id.into(),
        }
    }
}

/// Response from enabling a service account key.
#[derive(Debug, Clone)]
pub struct EnableServiceAccountKeyResponse {
    /// The re-enabled key.
    pub key: ServiceAccountKey,
}
