openapi: 3.1.0
info:
  title: Pistachio Admin API
  description: |
    Administrative API for managing Pistachio projects and resources.
    Requires service account authentication.
  version: 0.1.0
  contact:
    name: Pistachio Team

servers:
  - url: https://admin.pistachiohq.com/v1
    description: Production server
  - url: https://admin.staging.pistachiohq.com/v1
    description: Staging server

tags:
  - name: Projects
    description: Project management operations

paths:
  /projects:
    $ref: './paths/admin/projects.yml#/projects'

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: './components/security.yml#/ApiKeyAuth'
    ServiceAccountAuth:
      $ref: './components/security.yml#/ServiceAccountAuth'

security:
  - ApiKeyAuth: []
    ServiceAccountAuth: []
