openapi: 3.1.0
info:
  title: Pistachio API
  description: |
    API for end-to-end encrypted applications.
  version: 0.1.0
  contact:
    name: Pistachio Team

servers:
  - url: https://api.pistachiohq.com/v1
    description: Production server
  - url: https://api.staging.pistachiohq.com/v1
    description: Staging server

tags:
  - name: Health
    description: Service health checks
  - name: Auth
    description: Authentication validation endpoints

paths:
  /health:
    $ref: './paths/health.yml#/health'
  /auth/validate-key:
    $ref: './paths/auth.yml#/validate-key'
  /auth/validate-token:
    $ref: './paths/auth.yml#/validate-token'
  /auth/validate-service-account:
    $ref: './paths/auth.yml#/validate-service-account'

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: './components/security.yml#/ApiKeyAuth'
      description: API key for client SDK operations
    BearerAuth:
      $ref: './components/security.yml#/BearerAuth'
      description: ID token (JWT) for authenticated operations
    ServiceAccountAuth:
      $ref: './components/security.yml#/ServiceAccountAuth'
      description: Service account credential for admin operations
