//! OpenAPI client for Pistachio REST API.
//!
//! Code generated by openapi-generator at build time.
//!
//! Using openapi-generator instead of progenitor due to OpenAPI 3.1 support.
//! See: <https://github.com/oxidecomputer/progenitor/issues/762>

// Suppress clippy warnings on generated code
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::needless_return)]
#![allow(clippy::derivable_impls)]

mod generated;

pub use generated::apis;
pub use generated::models;
