# Project Schemas for Admin API

Project:
  type: object
  description: |
    Top-level container for apps, users, and resources.
    Projects provide isolated namespaces for authentication, data storage,
    and other platform services.
  properties:
    name:
      type: string
      description: Resource name in the format "projects/{project_id}".
      example: projects/my-project
    projectId:
      type: string
      description: Unique project identifier. Immutable after creation.
      pattern: '^[a-z][a-z0-9-]{4,28}[a-z0-9]$'
      example: my-project
    pistachioId:
      type: string
      description: |
        Internal project identifier.
        16 bytes encoded as 32 hex characters ending in '01'.
      example: a1b2c3d4e5f6789012345678901234501
    displayName:
      type: string
      description: Human-readable display name. Max 64 characters.
      maxLength: 64
      example: My Project
    state:
      $ref: '#/ProjectState'
    resources:
      $ref: '#/ProjectResources'
    createdAt:
      type: string
      format: date-time
      description: Timestamp when the project was created.
      example: "2024-01-15T10:30:00Z"
    updatedAt:
      type: string
      format: date-time
      description: Timestamp when the project was last updated.
      example: "2024-01-15T10:30:00Z"

ProjectState:
  type: string
  description: Lifecycle state of a project.
  enum:
    - ACTIVE
    - DELETED
  example: ACTIVE

ProjectResources:
  type: object
  description: Default resources provisioned for a project.
  properties:
    hostingSite:
      type: string
      description: Default hosting site name.
      example: my-project.pistachiohq.com
    realtimeDatabaseInstance:
      type: string
      description: Default realtime database instance name.
      example: my-project-default-rtdb
    storageBucket:
      type: string
      description: Default storage bucket.
      example: my-project.pistachiohq.storage

# Request/Response Messages

CreateProjectRequest:
  type: object
  description: Request body for creating a new project.
  properties:
    projectId:
      type: string
      description: |
        Desired project ID. If not provided, one will be generated.
        Must be 6-30 characters, lowercase alphanumeric with hyphens.
      pattern: '^$|^[a-z][a-z0-9-]{4,28}[a-z0-9]$'
      maxLength: 30
      example: my-new-project
    displayName:
      type: string
      description: |
        Human-readable display name.
        If not provided, projectId will be used as the display name.
      maxLength: 64
      example: My New Project
  example:
    projectId: my-new-project
    displayName: My New Project

CreateProjectResponse:
  type: object
  description: Response containing the newly created project.
  properties:
    project:
      $ref: '#/Project'
